### ISSUE TITLE
Detail how input components work with FieldArray?

### ISSUE THREAD

**Issue by ffMathy** [fabian-hiller/modular-forms#107]
I am following the very well-written documentation (thank you for that)!

However, it seems there is one area missing in this page: https://modularforms.dev/qwik/guides/input-components

And that is, how to make input components with FieldArrays. I am having a hard time getting it done. What do the props look like etc?

**Comment by fabian-hiller** [comment]
I don't quite understand what information you're looking for. I don't use any special components for field arrays. Maybe my example code of the todos and nested form from playground will help: https://stackblitz.com/edit/modular-forms-qwik

**Comment by ffMathy** [comment]
Just realized it was because I somehow thought it wasn't necessary to wrap the contents of "FieldArray" with a "Field", so I wasn't sure how to access the field props. Looking at the examples indeed helped. Thanks.

**Comment by fabian-hiller** [comment]
For more details see this guide: https://modularforms.dev/qwik/guides/field-arrays
