### ISSUE TITLE
onFormComplete for modular forms?

### ISSUE THREAD

**Issue by ciprianmacovei** [fabian-hiller/modular-forms#111]
is there an onFormComplete for modular forms in qwikjs, I really need some kind of event to make a get req after the form is successfully submitted.
thank u

**Comment by ciprianmacovei** [comment]
plus on qwikjs for init values I need to use routerLoader, globalAction seems to not work as expected and I have the following example where routerLoader is not the best approach:

I have a component that is standalone and it s doing what it does best adds stuff, and this component is not on a specific route, and for that purpose, I need to add the routerLoader in the layout and import it in the standalone component, and that is bad because every time I navigate the routerLoader is loaded.
Any ideas or design patterns are really really helpful.
Thank u very much.

**Comment by fabian-hiller** [comment]
What exactly does the get request do when the form is successfully submitted? Depending on this you have different options.

As described [here](https://modularforms.dev/qwik/guides/create-your-form#static-values), you can pass any object with a `value` property as initial values of your form.
