### ISSUE TITLE
Qwik - Example to show confirmation dialog before submitting the form

### ISSUE THREAD

**Issue by Cecildt** [fabian-hiller/modular-forms#120]
Hi, is there an example code to show a confirmation dialog before submitting the form to the server? The reason is to confirm if the user wants to submit the form values. If yes, continue to submit the form to the server. Otherwise, cancel the form submission. 

I'm using the Qwik framework to build an application.

**Comment by fabian-hiller** [comment]
No, we do not currently have such an example. However, this has nothing to do directly with Modular Forms. You can add the dialog and the required logic to your app on your own. Basically, a button must open the dialog, which then contains the final submit button.
