### ISSUE TITLE
Type 'Date' is not assignable to type FieldValues

### ISSUE THREAD

**Issue by JustGreg** [fabian-hiller/modular-forms#13]
Is there a way to use Date types in modular-forms? like this:

```typescript
const customerSchema = z.object({
  customerId: z.coerce.number().int().positive(),
  firstName: z.coerce.string().max(45),
  lastName: z.coerce.string().max(45),
  email: z.coerce.string().max(50).email(),
  lastUpdate: z.coerce.date().nullish(),
});

const customerForm = createForm({
  validate: zodForm(customerSchema),
});
```

Error:
```
Property 'lastUpdate' is incompatible with index signature.
  Type 'Date | null' is not assignable to type 'FieldValues | FieldValue | FieldValue[] | FieldValues[]'.
    Type 'Date' is not assignable to type 'FieldValues | FieldValue | FieldValue[] | FieldValues[]'.
      Type 'Date' is not assignable to type 'FieldValues'.
        Index signature for type 'string' is missing in type 'Date'.

validate: zodForm(customerSchema),
                  ~~~~~~~~~~~~~~
```

**Comment by fabian-hiller** [comment]
Currently the date object is not supported. I remember that before the library became public, I had implemented it. However, as far as I can remember, this had caused problems. Maybe it was because the `<input>` element does not accept a date object as a value and the constant conversion between the date object and a date string causes problems. So I recommend you leave the date value as a string and do the conversion to a date object afterwards.

```ts
const customerSchema = z.object({
  customerId: z.coerce.number().int().positive(),
  firstName: z.coerce.string().max(45),
  lastName: z.coerce.string().max(45),
  email: z.coerce.string().max(50).email(),
  lastUpdate: z.coerce.string().regex(/^(\d{4}-\d{2}-\d{2})?$/),
});

const handleSubmit = async (values: z.infer<typeof customerSchema>) => {
  const data = {
    ...values,
    lastUpdate: values.lastUpdate ? new Date(values.lastUpdate) : null,
  };

  // More code here
};
```

**Comment by JustGreg** [comment]
Thank you for the explanation!

I will still try to use date and see if i run into problems :)
For typescript i change all date attributes to string attributes.
```tsx
type SwapDatesWithStrings<T> = {
  [k in keyof T]: Date extends T[k] ? (null extends T[k] ? string | null : string) : T[k];
};

type CustomerType = SwapDatesWithStrings<z.infer<typeof customerSchema>>;

createForm<CustomerType>({
  validate: zodForm(customerSchema as unknown as Zod.Schema<CustomerType>)
})

const handleSubmit = async (values: CustomerType) => {
  const data = customerSchema.parse(values);
}

<Field of={form} name="lastUpdate">
  {(field) => (
    <div>
      <input {...field.props} value={dayjs(field.value).format('YYYY-MM-DD')} type="date" />
      <div>{field.error}</div>
    </div>
  )}
</Field>
```

**Comment by JustGreg** [comment]
In my "workaround" it is not a string or undefined, its a date (i made typescript think its a string but its not).
I can't change the zod schema to string types because its used on many other parts of the app. Thats why i choose this ugly solution with "SwapDatesWithStrings" :)

**Comment by fabian-hiller** [comment]
I understand, however Modular Forms internally holds the value as a string. Therefore, as I said, I think you can also pass the value directly. However, I may be wrong.

**Comment by fabian-hiller** [comment]
I just want to mention that I fixed some types in our Zod implementation. Now it should be possible to use the `transform` method of Zod to transform e.g. a string into a date.
