### ISSUE TITLE
Are you able to validateOn individual fields instead of the entire form?

### ISSUE THREAD

**Issue by Excelsior2021** [fabian-hiller/modular-forms#131]

**Comment by fabian-hiller** [comment]
I think no, but you can create a workaround with `validate`. What is your use case?

**Comment by araqaee** [comment]
Hey.
First, Thank you Fabian about useful package, modular forms, and ofcourse looking for valibot!
And about question shall to say no it's not possible, you can set validation on different fields and components(e.g. by using props) but they should placed in Form.

**Comment by fabian-hiller** [comment]
Thank you! 💙

> And about question shall to say no it's not possible, you can set validation on different fields and components(e.g. by using props) but they should placed in Form.

I don't quite understand what you're trying to tell me.

**Comment by Excelsior2021** [comment]
Hi Fabian,

Thanks. I'll close the issue.
