### ISSUE TITLE
SolidJS: Defining Context&Provider using Modular Form elements

### ISSUE THREAD

**Issue by Nmans01** [fabian-hiller/modular-forms#139]
Hello!

Modular Forms has been useful so far for creating a singular component which contains all the inputs I need for a particular submission feature in my project. However, to make this component easier to maintain, I had decided to break into into multiple nested components, such that I can trade one excessively long file for multiple concise ones. Additionally, I decided to move the central state and logic of the form into one Context/Provider pair using Solid-Primitive's `createContextProvider` function.

To give an example: 
```ts
type InputType = {
    ...
}

const [ThingProvider, _useThingContext] = createContextProvider(()=> {
   const [formStore, Element] = createForm<InputType>({});

   const otherThing = ...
   const helper = () => ...

   return { formStore, Element, otherThing, helper };
});

// ensure context is defined
const useThingContext = invariant(_useThingContext, "error: context must be used within provider");

export { ThingProvider, useThingContext };
```

**The issue I've been met with is this**: attempting to export the context causes the TS server to crash repeatedly and give the error that the type of Element cannot be serialized, since it contains a circular type definition. Is there any straightforward workaround for this issue? It would make the use of Modular Forms much easier for dynamic and concisely written Solid components.

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I was not aware of the problem before and I don't know if there is a solution for it. Why don't you create the form in a parent component and pass is as props to the children?

**Comment by fabian-hiller** [comment]
Please try the following... Replace `useForm` with `useFormStore` und import `Form`, `Field` and `FieldArray` only as needed with the store of the form as the `of` prop.

**Comment by Nmans01** [comment]
Looks like this is something I missed from the docs, but it completely covers my issue. I was able to call `useFormStore` to define only my form store in the shared context and make it accessible to multiple separate components, in each of which I created some of the field elements using the `of` prop. Thank you for the help!
