### ISSUE TITLE
Zod Validation: required does not work

### ISSUE THREAD

**Issue by apollo79** [fabian-hiller/modular-forms#14]
I am using the zod validation integration for validating my form. 
When I focus an input, which is required, but has no other requirements, and leave it, no error shows up. It even doesn't show an error if I type something and remove it and then leave the input. 
(I don't know if there is an option to solve this or if it is a bug)

**Comment by fabian-hiller** [comment]
Here it depends on your validation strategy. By default, the first validation is done when submitting the form and from there on after each input. With `validateOn` and `revalidateOn` you can control this behavior. You can find more about this in the [validation guide](https://modularforms.dev/guides/validate-your-fields) and the [API reference](https://modularforms.dev/api/createForm). Does that solve your problem?

**Comment by apollo79** [comment]
I am currently using the validation after "change". 
I also tried setting `revalidateOn` to "input", but it still validated after `change`, meaning only after leaving the field. Is this intended? 

I think an option for validation after the field has been touched would be good. I am used to be this from e. g. `felte` and forms I have filled out.

**Comment by fabian-hiller** [comment]
Yes, this is the expected behavior. `'input'`, `'change'` and `'submit'` follow the native DOM events here. `validateOn` defines the behavior before the form is submitted and `revalidateOn` the validation strategy after that. I agree with you that there should be a mode that validates fields once they are touched. I plan to implement this tomorrow.

**Comment by apollo79** [comment]
Nice! There might be a problem with which event to use, because the behaviour with validating after `touched` would be possible with `input` and `change`. Or will you make it a completely different option?

**Comment by apollo79** [comment]
> `validateOn` defines the behavior before the form is submitted and `revalidateOn` the validation strategy after that

I didn't see this in the documentation. Is it mentioned anywhere? 
I thought that when I set `validateOn` to `change` and `revalidateOn` to `input`, the revalidation would be after the first change made to the input, which would make sense to. Maybe this could be another feature? 
`revalidateOn` after the first submit makes sense to me if the first validation happens with the submit event, but if I chose `change` , I would expect it to apply to every input after the first `change` event.

**Comment by fabian-hiller** [comment]
> Nice! There might be a problem with which event to use, because the behaviour with validating after touched would be possible with input and change. Or will you make it a completely different option?

I would implement `touched` so that the first validation occurs at the `blur` or `input` event of a field and from then on after each `input`. What you describe with `touched` in combination with `change` is basically a validation that always happens on the `blur` event. I could add this as a separate mode.

> I didn't see this in the documentation. Is it mentioned anywhere?

I linked the pages where it is described in my first comment on the issue.

> `revalidateOn` after the first submit makes sense to me if the first validation happens with the submit event, but if I chose `change`event, I would expect event `revalidateOn` to apply to every input after the first `change` event.

Thats a good point. Thank you for mention it. I had been using React Hook Form's `reValidateMode` option as a guide here. I will think about your thought.

**Comment by fabian-hiller** [comment]
I think the UX for most forms is best if the initial validation is done either when a field is touched and from there on after each input, or on submission. After a form is submitted and has errors, validation should occur after each input to provide direct feedback to the user. If `validateOn` and `revalidateOn` worked as you expected and the first value was set to `submit` and the second to `input`, this would result in only fields that already have an error being validated on input after the form is submitted. Fields that do not have an error, but are subsequently changed, will not be validated until the next submission. I think this is a bad UX. However, I think your thoughts are right and hope that together we can come up with a better solution than the current one.

**Comment by apollo79** [comment]
Why aren't fields without errors validated on `input` after the submission? I thought that there were no differences for fields with errors and without (https://github.com/fabian-hiller/modular-forms/blob/main/packages/solid/src/utils/validateIfNecessary.ts#L39)?

**Comment by fabian-hiller** [comment]
Yes, currently that is the case. However, if validation worked the way you thought it would, it would be different because then the revalidation of a field would only happen if the field already had an error once.

**Comment by fabian-hiller** [comment]
Should I add `touched` and `blur` building on the current system with `validateOn` and `revalidateOn` or do you have a suggestion that would improve the current validation system in general?

**Comment by apollo79** [comment]
They would be a good addition for sure, but from my feeling the `reavlidateOn` option should build on the `validateOn` option. However, I understand, that this is tricky. `submit` happens on the form, while the other events happen on the inputs. So each one would have to be handled differently.

**Comment by apollo79** [comment]
It would probably be a little bigger change in the code base. But it would maybe provide a solution to the problem with `validateOn`: `submit` and `revalidateOn`: `input`, that you mentioned above

**Comment by apollo79** [comment]
But I would have to dig a bit deeper to find a solution. 
Or did you already come up with one?

**Comment by apollo79** [comment]
No, not really. `felte` doesn't have this option afaik. But I think it is a weird behaviour too, if a form validates everything after `change`, and suddenly after submitting, it validates after `input`.

**Comment by apollo79** [comment]
I don't know if there is a need for a completely new mechanism, but I think there should be the possibility to validate after change and the after each input as this is hoe much forms work.

**Comment by apollo79** [comment]
And if it remains like it is now I think it should be explicitely mentioned, that `revalidateOn` applies after submitting the first time. Currently it only speaks about the defaul behaviour.

**Comment by fabian-hiller** [comment]
Yes, I understand that. Maybe we should implement it as follows. `reavlidateOn` builds on `validateOn`. `validateOn` is the initial trigger and `revalidateOn` defines what happens after that. If `validateOn` is set to `submit` and the form has been submitted, `revalidateOn` is applied to all fields afterwards. There, it depends on the state of the form. For all other values of `validateOn` it refers to the state of the field and `reavlidateOn` is only applied if the current input of the field is invalid.

**Comment by apollo79** [comment]
Yes, that would be my approach too. Sounds good! 👍

**Comment by apollo79** [comment]
Which additional modes will you add?

**Comment by fabian-hiller** [comment]
I plan to add `touched` and `blur`.

**Comment by fabian-hiller** [comment]
`blur` is triggered when a field lose focus and `change` is triggered when a field with a changed input lose focus.

**Comment by apollo79** [comment]
> `blur` is triggered when a field lose focus and `change` is triggered when a field with a changed input lose focus.

And what will be the difference between `touched` and `blur`. `touched` doesn't sound like an event, so will it only happen once?

**Comment by fabian-hiller** [comment]
`touched` triggers validation on the `input` and on the `blur` event. Basically whenever you touch the field.

**Comment by apollo79** [comment]
> `touched` triggers validation on the `input` and on the `blur` event. Basically whenever you touch the field.

Ah, ok. It's maybe a bit weird naming, because it is the only option in the "past" and not as self-explaining as the other ones. But `touch` isn't really better.

**Comment by fabian-hiller** [comment]
Yes, I agree. But `touched` describes it best and since the form and its fields also have a touched state, we should choose this word.

**Comment by apollo79** [comment]
Yes, seems reasonable 👍

**Comment by fabian-hiller** [comment]
The changes are live! Thanks again for your help! Let me know if you run into any other problems.

**Comment by apollo79** [comment]
Wow, cool, just updated and changed the validation modes to `blur` and `input` and it works! Awesome!
