### ISSUE TITLE
Qwik formAction$ not being triggered when using useFormStore

### ISSUE THREAD

**Issue by anxhirr** [fabian-hiller/modular-forms#141]
I recently started using qwik with modular-forms. I was using useForm Api and everything was working pretty good. Later then I found the need to create a reusable form component to use in my /new /edit /duplicate routes. So, I replaced useForm with useFormStore based on the provided example from docs.

The issue that I am facing now is that the formAction$ is not being triggered although i have passed it as an option to useFormStore.

```javascript
export default component$(() => {
  const loginForm = useFormStore<ItemForm, ResponseData>({
    loader: useFormLoader(),
    action: useFormAction(),
    validate: valiForm$(ItemSchema),
  });

  return <AdvancedItemForm loginForm={loginForm} />;
});

``` 

this is my formAction:
```typescript
export const useFormAction = formAction$<ItemForm, ResponseData>(
  async (values) => {
    console.log("values", values);
    // i had my prisma logic here but i removed it for this example
  },
  valiForm$(ItemSchema),
);
``` 

The form is beign submitted, becouse loginForm.submitCount or loginForm.submitting props change when i click the submit button. also the client submit handler gets triggered, only the server one seems to not be working for some reasons. 

Below is the <AdvancedItemForm /> component which gets passed the loginForm:

```typescript
type Props = {
  loginForm: FormStore<ItemForm, ResponseData>;
};

export const AdvancedItemForm = component$(({ loginForm }: Props) => {
  return (
    <Form of={loginForm}>
      <Field of={loginForm} name="name">
        {(field, props) => (
          <div>
            <input
              {...props}
              value={field.value}
              type="text"
              placeholder="Name"
              class="input input-bordered w-full max-w-xs"
            />
            {field.error && <div>{field.error}</div>}
          </div>
        )}
      </Field>
      {/* i removed the other fields for this example */}
      <button type="submit" class="btn">
        {loginForm.submitting ? "Loading..." : "Save"}
      </button>
    </Form>
  );
});
``` 

Not sure whats going on, this is the second day of me trying to fix it haha.
I hope I provided enought information. Check my repo (src/routes/items) for the full code: https://github.com/anxhirr/qwik-pos
Thanks in advance

**Comment by fabian-hiller** [comment]
`useForm` automatically connects your form to the `Form` and `Field` components. With `useFormStore` you have to do this yourself using the `of` and `action` props. In your case, you need to pass your action to the `action` prop of the form component.

I will investigate if we can add `action` to the `FormStore` so that in the future it will be sufficient to pass only the `of` prop.

**Comment by anxhirr** [comment]
Thanks for the insanely fast reply, it's working now.
Keep up the great work!

**Comment by brandonpittman** [comment]
This had me stuck for a while just now. Assumed passing `of={form}` was sufficient. There's no type error when you pass `of` but not `action`.

**Comment by fabian-hiller** [comment]
This was necessary in the early days of Modular Forms. Since we updated the API this spring, it is no longer necessary with `useForm`. It is still needed with `useFormStore` (the API we used before). `useFormStore` is used in `useForm`. useForm` just makes the API nicer for the developer.
