### ISSUE TITLE
Zod validation: validateOn: "input" causes errors on any input

### ISSUE THREAD

**Issue by apollo79** [fabian-hiller/modular-forms#15]
When I set the `validateOn` option of `createForm` to "input", the form has a "Required" / "Invalid input" error for every field.

![errors](https://user-images.githubusercontent.com/90517340/211075266-8bd8678e-f258-4eb7-bbc0-63dffbdfc65c.png)

**Comment by fabian-hiller** [comment]
You're right, it shouldn't be like that. The validation should only happen after an input. I'll check the code and keep you updated here.

**Comment by AshSimmonds** [comment]
Cool - thought it was just I had funky data pre-population or something, switched out for `onChanged` for now.

**Comment by fabian-hiller** [comment]
Should be fixed now. Thanks for pointing out the problem!
