### ISSUE TITLE
qwik: toTrimmed return value rise error question

### ISSUE THREAD

**Issue by saberuster** [fabian-hiller/modular-forms#153]
Hello, 
I am encountering an issue while using the toTrimmed function in my code. Here is an example of how I am using it:
```jsx
      <Field name="test2" transform={toTrimmed({ on: "input" })}>
        {(field, props) => <input {...props} type="text" value={field.value} />}
      </Field>
```

However, I am getting an error, and you can view the screenshots:
![image](https://github.com/fabian-hiller/modular-forms/assets/27812324/9de536ca-2944-4500-aaff-d140abb2dda5)
![image](https://github.com/fabian-hiller/modular-forms/assets/27812324/3f7bbc45-0fc9-49e9-bc3c-5fe600a39ae9)

Upon inspecting the source code https://github.com/fabian-hiller/modular-forms/blob/main/packages/qwik/src/transformation/toTrimmed.ts , I noticed that
`toTrimmed` is return as type `TransformField<TValue>`, and it is not wrapped with QRL. 
However, the documentation at [this link](https://modularforms.dev/qwik/api/toTrimmed) states that the return type should be QRL<TransformField>. There seems to be a discrepancy between the documentation and the source code.
i alse check doc in https://modularforms.dev/qwik/api/toTrimmed, the return type is `QRL<TransformField>`. it seems different between doc and source code.

As someone who is new to Qwik and Modular Forms, I would like to confirm whether my usage of toTrimmed is correct？ or if there is a mistake that I need to work around?

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I think it is a bug. I am not sure how this could happen. I am sure I have tested it. Anyway, I will release v0.21.2 in the next few minutes which will solve this issue. Thank you for trying out Modular Forms!
