### ISSUE TITLE
Qwik Change/Focus events are deprecated

### ISSUE THREAD

**Issue by DustinJSilk** [fabian-hiller/modular-forms#159]
It looks like Qwik has deprecated the QwikChangeEvent and QwikFocusEvent (and other similar ones).

It would be helpful if ModularForms matched the updated types.

Thanks for all the hard work maintaining this great library!

**Comment by fabian-hiller** [comment]
Thank you! I will try to fix that in the next 24 hours.

**Comment by fabian-hiller** [comment]
v0.22.0 is available
