### ISSUE TITLE
Add `solid` export

### ISSUE THREAD

**Issue by apollo79** [fabian-hiller/modular-forms#16]
It is a [convention](https://twitter.com/RyanCarniato/status/1611605072299044865) for solid-js packages to ship the source code / JSX as an extra export, so solid can bundle the code itself in the end. [The tweet](https://twitter.com/RyanCarniato/status/1611605072299044865) mentions the [solid router package.json](https://github.com/solidjs/solid-router/blob/main/package.json#L21-L26) as an example, but in the [solid-lib-starter package.json](https://github.com/solidjs-community/solid-lib-starter/blob/main/package.json#L25-L34) they are doing even a few more exports.

Could this be added to modular-forms?

**Comment by fabian-hiller** [comment]
Thanks for the tip! I will take a look at it and improve it.

**Comment by fabian-hiller** [comment]
Thanks to your feedback, [Bundlephobia](https://bundlephobia.com/package/@modular-forms/solid@0.10.0) is now working. Next, I need to find a way to get the export analysis working as well.

**Comment by apollo79** [comment]
What exactly are you meaning with export analysis?

**Comment by fabian-hiller** [comment]
Bundlephobia provides an export analysis section. There you can check the bundle size of individual imports. This is particularly interesting for us as a modular library.

**Comment by apollo79** [comment]
Oh, yes, I see. Interesting. Do you have an idea why it fails to build?

**Comment by fabian-hiller** [comment]
No, the error message doesn't say anything and I couldn't find anything about it under the issues on GitHub.
