### ISSUE TITLE
Zod validation: `transform` results in type errors

### ISSUE THREAD

**Issue by apollo79** [fabian-hiller/modular-forms#17]
I want to use the `transform` method of zod validation to transform some values into numbers. However if I do so, I get type errors for the `validate` option of `createForm`. It has most likely something to do with different `input` and `output` types zod is able to handle. Modular forms is passing the `TFieldValues` to the`Output` generic type of `ZodType` in the definition of `zodForm` where it should probably pass it as `Input` generic type.

**Comment by fabian-hiller** [comment]
Is there a way to get the input type based on a schema?

**Comment by apollo79** [comment]
Yes, I think it's `z.input<typeof schema>`

**Comment by fabian-hiller** [comment]
Thank you very much for your help. The types should be fixed now.
