### ISSUE TITLE
Preact: What is the best method to pull values of fields in the form for using in computed()

### ISSUE THREAD

**Issue by otherjohn** [fabian-hiller/modular-forms#172]
Hi, I have a calculator form I am building
```
const calculatorForm = useFormStore<Inputs>({
    initialValues: {
      credit_rating: CREDIT_RATING.GOOD,
      down_payment_dollars: 0,
      down_payment_percentage: 0,
      down_payment_percentage_range: 0,
      disabled_vet: false,
      home_value: 300000,
      home_value_range: 300000,
      homeowners_insurance: 0.35,
      interest_rate: 0.06668,
      loan_term: 360,
      loan_type: LOAN_TYPE.PURCHASE,
      military_type: MILITARY_TYPE.REGULAR,
      propery_tax_rate: 1.2,
      refi_type: '',
      used_va_loan_before: false,
    },
  })
  ```
  And I would like to use Preact's `computed()` to create a new value based on the form inputs. something like this:
  ```
  const apr = computed(() => {
  return getAPR(calculatorForm.home_value,calculatorForm.loan_term,calculatorForm.interest_rate);
});
  ```
  
  I can't figure out how to get the stored values from `useFormStore`. Can someone give me some directions?

**Comment by fabian-hiller** [comment]
Try out `getValue`: https://modularforms.dev/preact/api/getValue

**Comment by otherjohn** [comment]
Will that still make it reactive? 
Maybe I am doing it wrong, but I have tried the following without any luck. When home_value is updated, APR doesn't recompute.

```
const apr = computed(() => {
const home_value = getValue(calculatorForm,'home_value');
return getAPR(home_value,.....rest of stuff);
});
```

**Comment by fabian-hiller** [comment]
`getValue` is not compatible with `computed` because it contains side effects. Please try to use `useComputed`. I have prepared a code example for you: https://stackblitz.com/edit/modular-forms-preact-vi9war?file=src%2Fcomponents%2FTextInput.tsx,src%2Froutes%2Flogin.tsx%3AL20

**Comment by otherjohn** [comment]
This is exactly what I was looking for! Thanks!!!!!
