### ISSUE TITLE
[Question] Is it possible to have optional fields?

### ISSUE THREAD

**Issue by FujishigeTemma** [fabian-hiller/modular-forms#173]
I'm currently developing Google Forms-like web app with `@modular-forms/react` and valibot.

### Problem example

**Problem**
```ts
setValue(form, "items.0.data.question", "") // OK
setValue(form, "items.0.data.max_select", 3) // error: Argument of type 'number' is not assignable to parameter of type 'never'. ts(2345)
```

*Code*
My `FormSchema` definition looks like this.
```ts
const FormSchema = object({
  title: string(),
  ...
  items: array(FormItemSchema)
})

enum FormItemType {
  TEXT = 0,
  CHECKBOX = 1,
}

export const FormItemSchema = variant("type", [
  object({
    type: literal(FormItemType.TEXT),
    data: object({
      question: string(),
    }),
  }),
  object({
    type: literal(FormItemType.CHECKBOX),
    data: object({
      question: string(),
      max_select: number(),
    }),
  }),
])
```

And if I use this schema for `useFormStore`, inferred type for `items.0.data.max_select` becomes never. Are there any good solution or alternative way to define a schema like this.

**Comment by fabian-hiller** [comment]
You wrote "items.0.data.max_number" instead of "items.0.data.max_select", does this cause the problem? Also, when using arrays, I recommend using our specialized array functions. In your case you should probably use `replace`. Read more here: https://modularforms.dev/qwik/guides/field-arrays#use-array-methods

**Comment by FujishigeTemma** [comment]
> You wrote "items.0.data.max_number" instead of "items.0.data.max_select", does this cause the problem?

Sorry, I just made a mistake when I simplified my code for reproduction (fixed). So it was not in my actual code.

> Also, when using arrays, I recommend using our specialized array functions. In your case you should probably use `replace`.

Thank you for your advice! But unfortunately I got almost same error. For me, it seems that, with a object `{ x: string, y: number } | { x: string, z: boolean }`, inferred type of `x` is correct but types of `y, z` become `never`.

![image](https://github.com/fabian-hiller/modular-forms/assets/49122148/57462c64-5171-45cb-b2a5-e17834cd07b0)
![image](https://github.com/fabian-hiller/modular-forms/assets/49122148/17c79085-eb64-477f-ad48-36d845a5deba)

**Comment by fabian-hiller** [comment]
If you provide me your code via StackBlitz I can try to investigate it. Here is a template: https://stackblitz.com/edit/modular-forms-react?file=src/routes/login.tsx

**Comment by fabian-hiller** [comment]
Thank you! I plan to have a look on it on the weekend.

**Comment by fabian-hiller** [comment]
It seems that this is the normal behavior of TypeScript when working with unions. The `y` doesn't exist in every case, which is why TypeScript displays an error. A workaround might be to use `setValues`: https://modularforms.dev/react/api/setValues

```ts
setValues(u, { x: 'ok', y: 'also ok' });
setValues(v, { data: { x: 'ok', y: 'also ok' } });
```

**Comment by FujishigeTemma** [comment]
Make sense. Thank you!
