### ISSUE TITLE
`requestSubmit` is not a function on Safari < 16

### ISSUE THREAD

**Issue by brandonpittman** [fabian-hiller/modular-forms#183]
The `submit` function calls `requestSubmit`, but this method isn't available on iOS 15.4. Calling `form.submit()` doesn't jive with Qwik, sadly.

<img width="1180" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/967145/aac5be9c-d702-444a-8be0-1c86aaabc2f9">

Is there a workaround for programmatically submitting a form on older Safari's (with Qwik)?

**Comment by brandonpittman** [comment]
Found a polyfill for `requestSubmit` and that seems to get around this problem. If there isn't a mention of browser compatibility in the docs, there probably should be.

**Comment by fabian-hiller** [comment]
What is the polyfill? Maybe we should add some info to the API reference.

**Comment by brandonpittman** [comment]
https://github.com/javan/form-request-submit-polyfill

I dynamically imported this in a `useVisibleTask$` call in the root of my Qwik app and it seems to be working out fine.
