### ISSUE TITLE
valiForm doesn't execute custom validation properly

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [fabian-hiller/modular-forms#197]
Hello,

I'm using valibot with modular form to validate a form. When I try to validate a checkbox field like this : 

```js
custom((val: boolean) => {
    if (!field.required) {
      return true;
    }
  
    return val;
  }, 
  field.error"
)
```

It doesn't throws the errors when val is false which makes my field being valide when it should not.

It does work in the Valibot playground, so I assumed the problem if from the modular form adapter ?

**Comment by fabian-hiller** [comment]
Have you debugged the code? Does `field.required` have the correct value at validation time?

**Comment by Tanguy-Magnaudet** [comment]
I tested with a form and two checkbox fields, one of them is required, the other is not.

At validation time I have this : 
```js
custom((val: boolean) => {
    // When none of them is selected.
    console.log(field.required, val)
    // true, false  for the first field
    // false, false  for the first field

    if (!field.required) {
      return true;
    }
  
    return val;
  }, 
  field.error"
)
```

The first one should raise an error, but it does not, I don't understand why. I'd try to make a stackblitz to isolate the problem tomorrow.

**Comment by fabian-hiller** [comment]
Thank you for the info. I am happy to have a look at the StackBlitz and investigate the problem.

**Comment by Tanguy-Magnaudet** [comment]
Hello Fabian,

I could not reproduce the problem outside my project it has been fixed after refactoring the Schema generator.

I guess it was my bad and we can close the issue !
