### ISSUE TITLE
Form submitted when filed has error

### ISSUE THREAD

**Issue by Tatamethues** [fabian-hiller/modular-forms#199]
Schema
```tsx
export const profileDisplayNameSchema = v.object({
	displayName: v.string([
		v.minLength(8, "Too Short Display Name"),
		v.maxLength(32, "Invalid Display Name"),
	]),
});
```
```tsx
function Test() {
	const [form, { Form, Field }] = createForm<ProfileDisplayNameSchemaForm>({
		validate: valiForm(profileDisplayNameSchema),
	});

	const submitHanlder: SubmitHandler<ProfileDisplayNameSchemaForm> = async (
		values,
		event,
	) => {
		event.preventDefault();
                event.stopPropagation();
	};
	return (
		<Form action={updateDisplayName} method="post" onSubmit={submitHanlder}>
			<Field name="displayName">
				{(field, props) => {
					return (
						<div>
							<input
								{...props}
								value={field.value}
								data-invalid={field.error ? "" : undefined}
							/>
							{field.error && <div>{field.error}</div>}
						</div>
					);
				}}
			</Field>
		</Form>
	);
}

```
I found that if the form is valid, the `event.preventDefault()` works and the form is not submitted. However, if the filed is invalid, the form was submitted with the invalid value.
Is this a bug?

*Edit*
I looked at the source code. When the form is valid, onSubmit is called in `Form` 's [onSubmit](https://github.com/fabian-hiller/modular-forms/blob/23f613f987a205735ebe35c57d2435ae4cc65a49/packages/solid/src/components/Form.tsx#L99).

So is it ok to add `stopPropagation` when form is invalid?
```tsx
					if (await validate(form, options)) {
						await onSubmit(getValues(form, options), event);
					} else {
						event.stopPropagation();
					}
```

**Comment by fabian-hiller** [comment]
Can you send me a minimal reproduction on StackBlitz? Do you use SolidStart?

**Comment by Tatamethues** [comment]
Yes..I use solid start.
I just found a new problem. When use both action and onSubmit on Form component, useSubmission  in onSubmit(I use it to set error form error) will not get the result after submit since the action runs after onSubmit. So...no need to set the `stopPropagation`.
Instead I have to use useAction to submit the form value and useSubmission get the result.

We can close this issue.

BTW, The reason I want to use action on form is I want to use the native way to submit the form but I have not noticed that action runs after onSubmit.
