### ISSUE TITLE
formAction$ code is not executed if Form component has "class" attribute

### ISSUE THREAD

**Issue by phips-git** [fabian-hiller/modular-forms#201]
Hey there,

first of all, thank you for spending time on your libraries and providing them to the open-source community! :)

I'm currently using the library for setting up several forms and encountered the following problem, which took me a few days to narrow it down.

When I add the "class" attribute to the `Form`component provided by the `useForm`hook and define a `formAction$`, the code in the action doesn't get executed on the server.

When server-side-validation is added, the validation is executed. Even if the validation succeeds nothing more happens, there are no error logs etc.

```jsx
export const useFormSubmit = formAction$<TestForm>(async (formValues) => {
    // This is not executed!
    console.log(formValues);
}, valiForm$(TestFormSchema));

export default component$(() => {
    const [TestForm, { Form, Field }] = useForm<TestForm>({
        loader: useFormLoader(),
        action: useFormSubmit(),
        validate: valiForm$(TestFormSchema)
    });

    return (
        <Form class="space-y-4"> // "class" attribute seems to be causing this behavior
            <Field name="test">
                {(field, props) => (...)}
            </Field>
        </Form>
    )
})
```

As my VS Code Intellisense suggests that the "class" attribute is supported for the `Form`component, I suppose that this is not the intended behavior. Can you confirm this?

**Comment by fabian-hiller** [comment]
Sorry for the late reply? Were you able to resolve the issue?

**Comment by phips-git** [comment]
Hey, I closed the issue, because the class attribute is actually not causing the problem. 

Unfortunately, I still have problems in combination with the latest Qwik version. The code in the submit action hook is just not executed. It seems that the form is stuck, because the "validating" property of the form object is still set to true and not updated. This seems to prevent the hook function from being called.

**Comment by fabian-hiller** [comment]
I am sorry to hear that. This could be a signal bug in bug. Does it help to downgrade Qwik?

**Comment by phips-git** [comment]
I already tried to downgrade the same version as the modular forms playground, but without success.

I read that there was a bug with the validating state in the SolidJS version of the package, which you fixed last year. Could it be a similar case here for the Qwik version maybe?

**Comment by fabian-hiller** [comment]
I don't think so. I can investigate it if you send me a StackBlitz link. Here is a template: https://stackblitz.com/edit/modular-forms-qwik?file=src/routes/login/index.tsx

**Comment by phips-git** [comment]
Sure, I copied the important things of the corresponding index.tsx to this fork: [https://stackblitz.com/edit/modular-forms-qwik-zrkmwv?file=src%2Froutes%2Flogin%2Findex.tsx](https://stackblitz.com/edit/modular-forms-qwik-zrkmwv?file=src%2Froutes%2Flogin%2Findex.tsx)

Thank you for spending some time on this :)

**Comment by phips-git** [comment]
Just wanted to let you know, that I found the problematic part here, even though I still don't know why and how to work around it.
But importing Qwik's `useNavigate` hook and using it in the `useTask$` hook causes the submit promise to never resolve. But this seems to be a Qwik related issue any way.

**Comment by fabian-hiller** [comment]
Thanks for the info. Sorry, I am busy at the moment and have not had a chance to investigate it.
