### ISSUE TITLE
Prevent Double Submit

### ISSUE THREAD

**Issue by robodna** [fabian-hiller/modular-forms#206]
What is the 'ModularForms' way of preventing double-form submits?  

Thank you,

**Comment by fabian-hiller** [comment]
Can you describe in more detail what you mean by "double-form submits"?

**Comment by robodna** [comment]
The user click 'submit' twice.  The form should prevent double submits until the first submit either returns an error or success.

Best,

**Comment by fabian-hiller** [comment]
You can disable the submit button while `formState. submitting` is `true`: https://modularforms.dev/qwik/api/FormStore

**Comment by robodna** [comment]
I did think of that but it does not prevent from the form being submitted multiple times by pressing 'enter'.  It would be good to have a 'pending' signal.

**Comment by fabian-hiller** [comment]
> I did think of that but it does not prevent from the form being submitted multiple times by pressing 'enter'.

Are you sure about that?

**Comment by robodna** [comment]
Yes, if you have the focus on an input and press enter, it will submit the form.  I've added an external signal to solve the issue.

**Comment by robodna** [comment]
I think disabling the <button type="submit" prevents double-submits for double-clicks on the button and double-enter in an input field.  I suspect adding an onKeypress handler detecting the 'enter' keypress on a textarea input and having that handler call 'myform.submit' in JS would still cause a double-submit.  As you suggest, adding if (!formState.submitting) myForm.submit in the onKeypress event is the right solution in that case.  All good now, thanks.
