### ISSUE TITLE
Form action response is optional before form submit

### ISSUE THREAD

**Issue by adamayres** [fabian-hiller/modular-forms#207]
Hello Fabian,

Great library! I came across a seemingly minor issue that stumped me for a little bit. When using Qwik, the `FormStore` returned as the first element of the array returned by `useForm` specifies that it has a `response` property of type `FormResponse`:

```
response: FormResponse<TResponseData>;
```

If I attempt to output the `message` property of the `response` without a conditional (or optional chaining) then Qwik does not properly track and update this value after a form submission. The confusing part for me came because there was an eslint error when I used optional chaining on the form store (`loginForm.response?.message`):

```
ESLint: Unnecessary optional chain on a non-nullish value.(@typescript-eslint/no-unnecessary-condition)
```

<img width="930" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/207585/25811d5e-c9b1-4425-a597-3c528ec87655">

Should the type for the response be made optional here?

```
response?: FormResponse<TResponseData>;
```

Does not work:

```
export default component$(() => {
  // Use login form
  const [loginForm, { Form, Field }] = useForm<LoginForm>({
    loader: useFormLoader(),
    action: useFormAction(),
  });

  <Form>
    <div>{loginForm.response.message}</div>
```

Works:

```
export default component$(() => {
  // Use login form
  const [loginForm, { Form, Field }] = useForm<LoginForm>({
    loader: useFormLoader(),
    action: useFormAction(),
  });

  <Form>
    <div>{loginForm.response?.message}</div>
```

Repro:

https://stackblitz.com/edit/modular-forms-qwik-5wqtw6?file=src%2Froutes%2Flogin%2Findex.tsx

**Comment by fabian-hiller** [comment]
This problem is related to Qwik's `useStore` and not directly to Modular Forms. The problem is that we write to the `loginForm.response` property when we change the response. By adding a `?` you access this property and make it reactive. Unfortunately, this does not work if you only access `loginForm.response.message`. However, I think we will find a fix for this in the long run.

**Comment by adamayres** [comment]
Thanks for quick response, this makes sense. My solution was to render conditionally based on whether the status was an `error`.

```
formStore.response.status === 'error' && <div {...props}>{formStore.response.message}</div>
```
