### ISSUE TITLE
Nested form example better clarity

### ISSUE THREAD

**Issue by aquaductape** [fabian-hiller/modular-forms#21]
In Nested form under playground page, I assume that the buttons "Move first to end" and "Swap first two" to swap any items, when it only swaps Option items. This lead me to believe that this playground example or library was broken.

Easy solution is to include "Option" in button text, such as "Move first Option to end" and "Swap first two Options". But I know that visually it's not pleasing to see button with a lot of text, so I don't know the solution to make this example aseptically clearer.

<img width="871" alt="Screenshot 2023-02-21 at 11 11 59 AM" src="https://user-images.githubusercontent.com/29286430/220437248-11eb738d-2e8b-4dae-91e9-fe147e655542.png">

**Comment by fabian-hiller** [comment]
Thank you for your feedback. Do you think it might help if I display more than one option by default?

**Comment by aquaductape** [comment]
yeah that's the quickest best solution IMO
