### ISSUE TITLE
[solidjs][typescript] Getting typing right in the LoginForm example

### ISSUE THREAD

**Issue by nicoknoll** [fabian-hiller/modular-forms#219]
Hi, I'm just trying to get typing working but somehow even the LoginForm typescript example leads to errors.

My main issue is getting typing for the `FormStore<FieldValues>` right. One of the issues Intellij gives me is that it always requires the second argument (`Generic type 'FormStore' requires '2' type argument(s) `) which seems to be easy to fix. But even when this is fixed the fields "of" parameter always complains with `Type FormStore<LoginForm> is not assignable to type FormStore<TFieldValues, TResponseData> ` as well as the children render method `Type (field: any, props: any) => JSX.Element is not assignable to type <TFieldValues, TFieldName>(store: FieldStore<TFieldValues, TFieldName>, props: FieldElementProps<TFieldValues, TFieldName>) => JSX.Element `.

![Bildschirmfoto 2024-06-21 um 14 00 43](https://github.com/fabian-hiller/modular-forms/assets/1143670/0085dac2-30cb-4fcf-afb0-5f81686975a6)

Let me know if I can add any more information to reproduce this.

**Comment by fabian-hiller** [comment]
Can you send me a StackBlitz link? You can use this as a template: https://stackblitz.com/edit/modular-forms-solid?file=src/routes/login.tsx

**Comment by fabian-hiller** [comment]
Please make sure that the libraries you are using are up to date.

**Comment by nicoknoll** [comment]
Thanks for the fast reply. I copied the content from the guide (https://modularforms.dev/solid/guides/typescript) into stackblitz and it shows the same typescript errors (it is running though): https://stackblitz.com/edit/modular-forms-solid-dkgdkw?file=src%2Fapp.tsx,src%2FLoginPage.tsx

![Bildschirmfoto 2024-06-21 um 20 08 50](https://github.com/fabian-hiller/modular-forms/assets/1143670/7a676596-ee4c-435b-8c97-85fce8bf5de3)

**Comment by fabian-hiller** [comment]
Thank you very much! I will look into this issue. For now, here is a workaround: https://stackblitz.com/edit/modular-forms-solid-owzxu8?file=src%2Fapp.tsx,src%2FLoginPage.tsx

**Comment by nicoknoll** [comment]
Nice, thanks a lot so far!

**Comment by fabian-hiller** [comment]
This is fixed now. Thanks!
