### ISSUE TITLE
Storybook integration bug.

### ISSUE THREAD

**Issue by NorbertBodziony** [fabian-hiller/modular-forms#22]
Hey I am hitting same error as https://github.com/fabian-hiller/modular-forms/issues/8.
I am using storybook with vite plugin. Vite looks something like this.
```  
async viteFinal(config, { configType }) {
    config.plugins.unshift(Solid({ hot: false }))
    config.plugins.unshift(WindiCSS.default())
    config.plugins.unshift(tsconfigPath({ root: path.resolve(__dirname, '../') }))
    config.optimizeDeps = undefined
    const a = mergeConfig(config, {
      define: {
        'process.env.NODE_DEBUG': 'false'
      }
    })
    console.log(a)
    return {
      ...a,
      optimizeDeps: undefined
    }
  }
  ```
  As you can see i tried removing `optimizeDeps` but that did not worked for me.

**Comment by fabian-hiller** [comment]
Hey! Thank you for mentioning that. This looks like a problem with the configuration of your development environment. I don't think there is anything I can do about it. Post your question in the SolidJS Discord server. I'm sure someone there can help you.

**Comment by NorbertBodziony** [comment]
Just quick update from me. bumping `vite-plugin-solid` package solved problem.
