### ISSUE TITLE
Field onChange event

### ISSUE THREAD

**Issue by robodna** [fabian-hiller/modular-forms#227]
I created a custom component and dispatch the input.onChange event from inside my component.  The event does trigger, but for some reason, <Field does not seem to listen to onChange.  I need to add <MyComponent onChange={(e)=>setValue(myForm,'my_field',e.target.value)}   for it to work.

Any ideas on how I can get <Field to handle the onChange event instead of having to call it programatically?

**Comment by robodna** [comment]
Just so I understand the basics, the <Field element listens to 'JSX.EventHandler<FieldElement, Event>; onChange event.  
The native <input onChange uses a new Event and not a JSX.EventHandler<FieldElement,Event> right?   <Field seems to pass props.onChange to my custom component, and I assign <input {...props} to the native input element contained in my custom component.

**Comment by fabian-hiller** [comment]
You must connect the `props` with a native `<input />` element. It does not matter how deeply it is nested.

**Comment by robodna** [comment]
Does the onChange event on the internal input element not bubble up from inside the custom component up to Field?  

Looking at TextInput, it does not dispatch events and relies on Field to listen to the onChange bubbling up from inside the custom component.

**Comment by robodna** [comment]
More info:  The <input I use inside my custom element is hidden.  I programatically dispatch the onChange event when the hidden input's value is changed programatically:

`InputElementRef()?.dispatchEvent(new Event('change', {bubbles:true, composed:true}));
      `
So it does not work when I dispatch the change event programatically, but it DOES work if I set the hidden input's type to 'text' and enter characters into the <input box.  

Is there maybe something missing when I dispatch the event so cause <Field to ignore it?

**Comment by fabian-hiller** [comment]
I'm sorry, I don't know and have to research it myself. Unfortunately, I have no time for it at the moment.

**Comment by fabian-hiller** [comment]
Yes, I think you are right. We only capture inputs on `"input"` events. Is this a problem for you? Can you switch the event name?

**Comment by robodna** [comment]
It's not a problem for me now since I just dispatch the 'input' event type instead of 'change'.  Technically I think it's ok since the 'change' event is meant for when the input's focus is lost or when the 'enter' key is presses.  Programatically setting the value of a hidden contained in a custom component should dispatch 'input' and not 'change' so I think it's ok the way it is.
