### ISSUE TITLE
[Qwik] Zod async validation doesn't work

### ISSUE THREAD

**Issue by Martinusius** [fabian-hiller/modular-forms#233]
When using custom async validation function in zod (using `.refine`) the form throws an error saying that `.parseAsync` should be used for the validation.

![image](https://github.com/user-attachments/assets/a0019187-359d-4ca5-922e-f292c1ef3fac)

Async validation has many use cases. I personally encountered this issue while trying to implement username taken check during user registration.

The issue can presumably be traced to this file: [/packages/qwik/src/utils/getParsedZodSchema.ts](../blob/main/packages/qwik/src/utils/getParsedZodSchema.ts)

![image](https://github.com/user-attachments/assets/811185d3-c87c-4a73-acde-0d9537cfc460)
In this file the `.safeParse` function is always used to parse the data, even when async validation is needed. 

It seems however that a very simple fix is possible:
![image](https://github.com/user-attachments/assets/d6d3acab-a66c-48f1-bcc0-404b558171c7)
We can always use the async version `.safeParseAsync` instead since the original function is always async anyway.

As far as I know this approach has no downsides and successfully fixes the issue at hand.

**Comment by fabian-hiller** [comment]
I am not sure why I did not implement it with `. safeParseAsync`. I think there was a reason, but I am not sure anymore. I will see if I can change it to `.safeParseAsync` and release a new version. As a workaround you can simply copy the code, change it to the async version and use your own adapter until the new version is available.

**Comment by fabian-hiller** [comment]
A new version is available
