### ISSUE TITLE
The `valiForm$` validator shows error for valid empty input if once it caused an error.

### ISSUE THREAD

**Issue by genki** [fabian-hiller/modular-forms#238]
Here's reproduction code.
https://stackblitz.com/edit/modular-forms-qwik-p9vjtz?file=src%2Froutes%2F(default)%2Flogin%2Findex.tsx

At first, please submit the form and check if the email field causes no error at that field if it is blank.
Second, type something wrong email string in the email field and check if it causes error expectedly.
Finally, back it to blank and check if it accepts blank string as expected.

**Comment by genki** [comment]
This error revives when on submit even if I manually `clearError(...)` it.

**Comment by fabian-hiller** [comment]
This behavior is intended. Initially the state is `undefined`. This is covered by `optional` in your schema. After typing into the field, the datatype changes to `string`. After removing the text, the datatype is still `string`, but it is now an empty string. An empty string is not a valid email address. Therefore, you must change your schema to allow empty strings.

I recommend to change the initial value of email in your loader to an empty string and change your Valibot schema to the following. Try it out in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6AK6tgbABQBtDGPIw+UMrMKEAlABpxYYGD6ylHKMFYBzWXvEDkwUre0BdbQ2ZsOcKH1QSpPCiZsjYfAAKyFCoJtz8gvpaHnAA9KlwADwAtHAAwjzI1nxwlmAS8Px+jCzsEKR8yhA2fgFBHkA).

```ts
import * as v from 'valibot';

const Schema = v.union([v.literal(''), v.pipe(v.string(), v.email())]);
```

Related link:
- https://valibot.dev/guides/unions/
- https://valibot.dev/api/union/
- https://valibot.dev/api/literal/

**Comment by genki** [comment]
Thank you for the answer.
I have tested the example, but it causes error.
I had to modify it to like this:

```ts
const LoginFormSchema = object({
  email: optional(union([literal(""), pipe(string(), email())])),
  password: pipe(string(), minLength(1))
})
```

**Comment by fabian-hiller** [comment]
Have you also changed the initial data in your loader to an empty string?

**Comment by genki** [comment]
@fabian-hiller 
I had not. Fixed and I tried again, then no error happened.
Thanks!
