### ISSUE TITLE
Valibot array schema not working as intended

### ISSUE THREAD

**Issue by floratmin** [fabian-hiller/modular-forms#252]
I have a kobalte multi select where the unselected state is `['']` where at least one option has to be selected. For this I create a schema with valibot:

```
 v.pipe(v.array(v.pipe(v.string(), v.nonEmpty())), v.nonEmpty())
```

While not validating in the valibot playground, the form validates. When I write a custom check it works as intended: 

```
 v.pipe(v.array(v.string()), v.check((v: string[]) => v.length > 0 && v[0] !== '', 'Required'))
```

**Comment by fabian-hiller** [comment]
Can you share the Valibot playground that is not working as intented?

**Comment by floratmin** [comment]
It works in the playground, but not when used with modular forms.

**Comment by fabian-hiller** [comment]
Can you check if it works after executing `v.setGlobalConfig({ abortPipeEarly: false })` in the global scope?

**Comment by fabian-hiller** [comment]
The problem may be that Modular Forms enables the `abortPipeEarly` configuration by default. Can you try wrapping your schema in `v.config(schema, { abortPipeEarly: false })`?

**Comment by floratmin** [comment]
No. it does not make any difference.

**Comment by floratmin** [comment]
Thank you, this worked.
