### ISSUE TITLE
solid: cannot use without valibot

### ISSUE THREAD

**Issue by obedm503** [fabian-hiller/modular-forms#255]
valibot is an optional peer dependency and marked as external in the rollup config but is still imported by the generated esm output target.

To prevent this, the modules that use valibot should not be re-exported by the `index.ts` file. These files should be accessible via `@modular-forms/solid/valibot` instead.

![image](https://github.com/user-attachments/assets/0e98f558-c6f2-4838-863e-8d797819cec9)

Related to this:

`v0.24.0` has valibot version `1.0.0-beta.0` as a dev dependency but version `^1.0.0` as a peer dependency. But valibot version `1.0.0` does not exist in the npm registry (yet?). This confuses npm and causes it to fail making modular forms impossible to use. This is the error:

```sh
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @modular-forms/solid@0.24.0
npm WARN Found: valibot@1.0.0-beta.0
npm WARN node_modules/valibot
npm WARN   valibot@"1.0.0-beta.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional valibot@"^1.0.0" from @modular-forms/solid@0.24.0
npm WARN node_modules/@modular-forms/solid
npm WARN   @modular-forms/solid@"^0.24.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @modular-forms/solid@0.24.0
npm WARN Found: valibot@undefined
npm WARN node_modules/valibot
npm WARN   valibot@"1.0.0-beta.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional valibot@"^1.0.0" from @modular-forms/solid@0.24.0
npm WARN node_modules/@modular-forms/solid
npm WARN   @modular-forms/solid@"^0.24.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for valibot@^1.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by fabian-hiller** [comment]
Thank you for creating this issue. I will try to have a look at it on Wednesday. Please downgrade to the previous version in the meantime.

**Comment by fabian-hiller** [comment]
This should be fixed now.

**Comment by obedm503** [comment]
The issue now is that valibot gets installed and bundled even if I don't need it. Any chance you can separate the module that uses valibot under a separate `exports` key? Maybe that way it will get tree-shaken out of my bundle. Ideally, it would also be a peer dependency instead of direct one. What do you think?

**Comment by fabian-hiller** [comment]
Are you sure it is being bundled? Your build step should tree-shake the modules and remove any dead code.
