### ISSUE TITLE
`reset` only works on fields where `initialValue` is set

### ISSUE THREAD

**Issue by floratmin** [fabian-hiller/modular-forms#257]
When using `reset` with controlled fields, it works only for fields which are created with `initialValues` in the form options.

**Comment by fabian-hiller** [comment]
Thank you for reaching out! What framework are you using?

**Comment by floratmin** [comment]
I am using Solidjs.

**Comment by fabian-hiller** [comment]
It works for me without initial values: https://stackblitz.com/edit/modular-forms-solid?file=src%2Froutes%2Flogin.tsx

**Comment by floratmin** [comment]
Thank you, I will investigate further.

**Comment by fabian-hiller** [comment]
Make sure your fields are controlled: https://modularforms.dev/solid/guides/controlled-fields
