### ISSUE TITLE
support for class-validator

### ISSUE THREAD

**Issue by sachaw** [fabian-hiller/modular-forms#26]
I have some external classes define the shape of some forms, as they are classes, inferring the shape of a Zod schema is non-trivial, I have previously used https://github.com/typestack/class-validator for validation, but I have run into the situation outlined in https://github.com/fabian-hiller/modular-forms/issues/2 are there any other workarounds that could enable this?

**Comment by fabian-hiller** [comment]
Can you share a code sample with me so that I can understand your problem even better?

**Comment by sachaw** [comment]
Thanks for the reply, here's an outline:

1. I define a schema that inherits from an external class: https://github.com/meshtastic/web/blob/master/src/validation/config/position.ts inherits from https://js.meshtastic.org/classes/Protobuf.Config_PositionConfig.html
2. I have a "form generator" that takes a generic and a schema to define the physical layout: https://github.com/meshtastic/web/blob/master/src/components/PageComponents/Config/Position.tsx
3. Finally the generator itself (currently using react-hook-form): https://github.com/meshtastic/web/blob/master/src/components/Form/DynamicForm.tsx https://github.com/meshtastic/web/blob/master/src/components/Form/DynamicFormField.tsx

Hopefully this is clear enough, thanks.

**Comment by fabian-hiller** [comment]
Is your problem that the derived type is an interface and Modular Forms throws an error when you pass it as generic or does your problem relate to validating the form inputs?

**Comment by sachaw** [comment]
The former. I am unable to use your previous guidance of using a type instead of an interface

**Comment by fabian-hiller** [comment]
Unfortunately, I don't know any solution for this at the moment. To make the form values type-safe even with nested objects and arrays, I use a recursive type and this approach leads to problems when using interfaces. I will ask for advice in the TypeScript Discord. However, it is uncertain if there is a solution for this as described in #2. I will report here as soon as I have an answer.

**Comment by fabian-hiller** [comment]
I received an answer in the TypeScript Discord and am now checking if the given solution works for Modular Forms.

**Comment by fabian-hiller** [comment]
I have been busy with other things the last few days. I hope to give you feedback on this over the weekend.

**Comment by sachaw** [comment]
No rush, thanks man

**Comment by sachaw** [comment]
Found a workaround:
The `yup` validation library has `ObjectSchema` that allows deriving a schema from an external class definition.
So maybe this issue can be converted to requesting support for `yup`

**Comment by fabian-hiller** [comment]
Thanks for the info! Do you have a code example? Do you also work with Yup and need adapters for validation with Modular Forms?

**Comment by fabian-hiller** [comment]
All solutions I know so far to be able to support interfaces reduce type safety. I have again experimented a bit, but have not come to a satisfactory solution.

**Comment by fabian-hiller** [comment]
I'm temporarily closing the issue until there are signs that changes to our code can fix the problem.
