### ISSUE TITLE
Invalid types for `valiForm`

### ISSUE THREAD

**Issue by CamilleHbp** [fabian-hiller/modular-forms#261]
I'm using `valibot` **v0.42.1** and `@modular-forms/solid` **v0.24.1**.

I get the following error when using a `Schema` for the `valiForm` function:

```sh
Type 'ObjectSchema<{ allTheFieldsFromMySchemaHere }, undefined>' is missing the following properties from type 'GenericSchema<unknown, unknown, BaseIssue<unknown>>': '~standard', '~vendor', '~validate
```

Are those two versions incompatible? Cheers! :)

**Comment by fabian-hiller** [comment]
Please upgrade to valibot v1.0.0-beta.2

**Comment by CamilleHbp** [comment]
That fixed it. Thanks! 🙏
