### ISSUE TITLE
Linked or one-of validations

### ISSUE THREAD

**Issue by smahs** [fabian-hiller/modular-forms#269]
I tried to look through the docs and issues to find something relevant but couldn't find anything on this. If this is covered already somewhere, please point me to it. This is likely an uncommon case for which there can be alternative solutions.

Suppose you have a type like this of which only one has to be valid, but not both:
```ts
type FileForm = {
	name: string;
	files?: File[];
	url?: string;
};
```

Both files and url have their own validators. In addition to validate exactly one of them is specified, I have a function called `validateOneOf` which validates and sets or clear the error on both these fields. This works fine for the one-of validation. However, this approach doesn't call the validator of the linked field. Suppose both these fields are defined which causes `validateOneOf` to fail for both the fields, and the user clears the file, then the active field is files for which both validators are executed and also clears the error on url if valid. But if the url value is not valid (non empty string which fails the `url` validator from this library), this approach will not validate the url field independently to set the error back.

I can use an effect to trigger validations on both the fields when the value on either changes (I haven't tried, but I think that should work). But I was thinking if it was a better approach if the library exposes a linked prop on the Field type to trigger both validations together? One-of is just an example, but there may be other use cases for this pattern (any-of is a subset of the above one-of example, or validating both password fields together in a password reset form).

**Comment by fabian-hiller** [comment]
Do you use our native validation functions? I am sure this is solvable when using a Valibot schema.
