### ISSUE TITLE
Server side validation support?

### ISSUE THREAD

**Issue by jmcelreavey** [fabian-hiller/modular-forms#29]
Hi 👋 

I'm curious and I couldn't see anything in the documentation but is it possible to pass back specific field errors from the server for example "Email address is already taken" 

Ideally, I'd like a way of returning that error so that the appropriate `field.error` gets updated.

Apologies if it is in the documentation and I missed in (Great job on that documentation though, it's really easy to follow)

**Comment by fabian-hiller** [comment]
Do you use SolidJS or Qwik?

**Comment by jmcelreavey** [comment]
Here's an example using `name` and on the `formAction$`  I want to return that the email is already taken and assign it to the correct property:

```
import { component$, useStylesScoped$, useSignal } from "@builder.io/qwik";
import { routeLoader$, z } from "@builder.io/qwik-city";
import {
  formAction$,
  useForm,
  zodForm$,
  type InitialValues,
} from "@modular-forms/qwik";
import ContactStyles from "./contact.css?inline";

const contactSchema = z.object({
  name: z.string().min(5),
  message: z.string().min(5),
});

type ContactForm = z.input<typeof contactSchema>;

export const useFormLoader = routeLoader$<InitialValues<ContactForm>>(() => ({
  name: "",
  message: "",
}));

export const useFormAction = formAction$<ContactForm>((values) => {
  // Return name already taken error
}, zodForm$(contactSchema));

export default component$(() => {
  useStylesScoped$(ContactStyles);
  const formVisible = useSignal(false);
  const [, { Form, Field }] = useForm<ContactForm>({
    loader: useFormLoader(),
    action: useFormAction(),
    validate: zodForm$(contactSchema),
  });

  return (
    <article>
      <h2>Contact</h2>
      <button onClick$={() => (formVisible.value = true)}>Contact Me</button>

      {formVisible.value && (
        <Form>
          <Field name="name">
            {(field, props) => (
              <>
                <label for={field.name}>Your name</label>
                <input {...props} type="text" />
                {field.error && <div>{field.error}</div>}
              </>
            )}
          </Field>
          <Field name="message">
            {(field, props) => (
              <>
                <label for={field.name}>Your name</label>
                <textarea {...props} />
                {field.error && <div>{field.error}</div>}
              </>
            )}
          </Field>
          <button>Send</button>
        </Form>
      )}
    </article>
  );
});
```

**Comment by fabian-hiller** [comment]
Yes what you have in mind is possible. Do you want the error message to appear at a field or in general, e.g. at the very end of the form? Do you want to use Zod for validation or validate this part manually in `formAction$`?

**Comment by jmcelreavey** [comment]
I'd like for it to appear at a specific field. i.e. the name `field.error` I don't mind validating manually in `formAction$` though if Zod could be used though to validate that for me it would be awesome.

**Comment by fabian-hiller** [comment]
In `formAction$` you could do the following:

```ts
export const useFormAction = formAction$<ContactForm>((values) => {
  if (names.includes(name)) {
    return {
      errors: { name: 'Name is already taken' }
    };
  }
}, zodForm$(contactSchema));
```

And with Zod, I would probably use `refine`:

```ts
const contactSchema = z.object({
  name: z.string().min(5).refine((name) => names.includes(name), 'Name is already taken'),
  message: z.string().min(5),
});
```

**Comment by fabian-hiller** [comment]
You may find these guides interesting:
https://modularforms.dev/guides/handle-submission
https://modularforms.dev/guides/enhanced-forms
https://zod.dev/?id=refine

**Comment by jmcelreavey** [comment]
Thanks for the reference material. I had hoped returning that error in the formAction would automatically update the appropriate field error in the form but that doesn't seem to have happened. Do I need to do something else?

**Comment by tuurbo** [comment]
It works for me. Have you updated to the latest version? https://github.com/fabian-hiller/modular-forms/releases

```tsx
export const useFormAction = formAction$<LoginForm>(async (values) => {
  return {
    errors: {
      email: 'taken!!', // <--- this shows below the email field
    },
    status: 'success',
    message: 'login failed',
  };
}, zodForm$(loginSchema));
```

**Comment by jmcelreavey** [comment]
Whoops, I haven't. That would explain it. Thanks!
