### ISSUE TITLE
Submit a form and hard redirect if successful (qwik)

### ISSUE THREAD

**Issue by tuurbo** [fabian-hiller/modular-forms#31]
Is it possible to force a hard page load from within formAction$ only when intentional. For example when calling `throw redirect()`? I'm not using "SPA" mode in Qwik.

```tsx
export const useFormAction = formAction$<LoginForm>(
  async (values, { redirect, fail }) => {
    const res = await fetch('/api/login');

    if (res.success) {      
      // do a hard refresh
      throw redirect(302, '/account');
    }

    return fail(400, {
      message: 'Login failed',
    });
  },
  zodForm$(loginSchema),
);
```

**Comment by fabian-hiller** [comment]
Have you already created the route for `/account` and can it be accessed?

**Comment by tuurbo** [comment]
Yes, I was using qwiks version of `<Form action={useSigninAction} reloadDocument>` prior to switching to the modular-forms version of Form. Problem is qwiks `reloadDocument` attribute would do a full page reload on every submit, but I only want it to if the login was successful and when redirecting away from /login to /account.

**Comment by fabian-hiller** [comment]
Thanks for the hint with the `reloadDocument` property. I will have another look at the Qwik City `Form` component to improve my code.

Do I understand you correctly that you want the "reload" only in certain cases? Is this only about redirecting to `/account`? Because that worked in my test without `reloadDocument` with Modular Forms `Form` component and `formAction$`.

**Comment by tuurbo** [comment]
> Do I understand you correctly that you want the "reload" only in certain cases? Is this only about redirecting to `/account`? Because that worked in my test without `reloadDocument` with Modular Forms `Form` component and `formAction$`.

Hmmm, that doesn't seem to be the behavior I'm having. I'll need to create a new qwik repo from scratch and see if I get a different result.

**Comment by fabian-hiller** [comment]
You can type `qwik.new` in your browser line to create a new StackBlitz project. You can share this with me so I can help you if needed.

**Comment by tuurbo** [comment]
repo: https://github.com/tuurbo/qwik-test

Here is a video showing the account page isn't being hard loaded at the end https://www.loom.com/share/325b089201274849a97897523e2f3f7a

I couldn't get stackblitz to even load for me.. https://stackblitz.com/github/tuurbo/qwik-test

**Comment by fabian-hiller** [comment]
> Do I understand you correctly that you want the "reload" only in certain cases? Is this only about redirecting to `/account`? Because that worked in my test without `reloadDocument` with Modular Forms `Form` component and `formAction$`.

I may have made a mistake here and the redirect was done without a reload. Best ask on Builder.io/Qwik Discord if it is technically possible to execute a reload whenever a certain condition is given.

For what reason do you need the reload. Doesn't it feel better for the user if the navigation is done via JavaScript?

**Comment by fabian-hiller** [comment]
I am closing the issue but am open to reopen it should changes to Modular Forms help with your problem.

**Comment by tuurbo** [comment]
> For what reason do you need the reload. Doesn't it feel better for the user if the navigation is done via JavaScript?

We have some 3rd party scripts that don't play nice with SPA's but I might need to make an exception in certain cases. I also found a case where context isn't passed correctly during client side navigation and I need to figure out if its me or a bug with qwik. For now I made a helper that redirects on form success.

```tsx
export const useRedirectFormOnSuccess = (form: FormStore<any, any, any>) => {
  useTask$(async ({ track }) => {
    track(() => form.response);
    if (isBrowser && form.response.status === 'success') {
      window.location.href = form.response.message!;
    }
  });
};

useRedirectFormOnSuccess(loginForm);
```

Thanks for all your help :)

**Comment by RaeesBhatti** [comment]
While the solution described above does work, I have to say it's not easy to figure out on your own. Maybe a better way of doing this would be something like:
```ts
const handlActionResponseInBrowser = function (response) {
  if (response.status === 'status') {
    location.href = '/account';
  }
}

const [loginForm, { Form, Field }] = useForm<LoginForm>({
  loader: useLoginFormLoader(),
  action: useLoginFormAction(),
  validate: zodForm$(loginSchema),
  actionResponseHandler: handlActionResponseInBrowser,
});
```

**Comment by BakauDesign** [comment]
You can use native redirect, example:
`useVisibleTask$(({ track }) => {
        const response = track(() => loginForm.response);

        if (response.status === 'success' || response.data?.success) {
            window.location.href = '/seller/dashboard'; 
        }
});`
