### ISSUE TITLE
Validate confirmation field (Qwik)

### ISSUE THREAD

**Issue by lbensaad** [fabian-hiller/modular-forms#32]
I have a registration form with the fields password and confirmPassword. In the `validate` property of confirmPassword, how to make it validate that its value is the same as the value of password. I tried this:
```
validate = value( getValue(form,"password"), "Password does not match");
```
 but `getValue` is returning `undefined` even when the password field is filled.

**Comment by fabian-hiller** [comment]
`value` is a function, so it probably won't be re-executed when the signal changes. The trick is to pass a callback and access the value in it. This gives you access to the value whenever the password is validated. Use the `custom` function for this and let we know it it works for you.

**Comment by fabian-hiller** [comment]
Would you like to write `form.values.password` instead of `getValue(form, 'password')`? Technically this is possible. However, it would increase the bundle size while keeping the functionality the same. Furthermore, it is part of the modular API design that additional functionality that is not always needed, such as `getValue`, is offloaded to a separate function.

**Comment by lbensaad** [comment]
Ok thanks @fabian-hiller. But I see that the custom callback is being called many times.Here is my custom validate:
```
export function sameAs(form: FormStore<any, any, any>, name: string, error: string) {
    return custom(
        $((value) => {
            const otherValue = getValue(form, name);
            console.log("Comparing ", value, " VS ", otherValue);
            return value === otherValue;
        }),
        error
    )
}
```
Here is how I use it
```
<InputField
            of={form}
            name="password"
            type="password"
            validate={[required("..."), minLength(6, "must be at least 6 symbols.")]}
            required
          />
<InputField
            of={form}
            name="confirmPassword"
            type="password"
            validate={[sameAs(form, "password", "the password is not the same")]}
            required
          />
```
When I type 123456 in the password field then when I type "1" in the confirmPassword field I see that sameAs is called once, and after I press "2" I see in the log that sameAs is called 3 times and when I type 3, it will be called 4 times etc.
Does my implementation have an error or is there a bug in the library?

**Comment by fabian-hiller** [comment]
Thank you for pointing this out. I will investigate this. Furthermore, I will change `custom` to `custom$` in one of the next updates, so you don't have to write `$(...)` anymore.

**Comment by lbensaad** [comment]
Good, thanks. 
Just deprecate `custom` and add `custom$` next to it

**Comment by fabian-hiller** [comment]
> But I see that the custom callback is being called many times.

Thank you for noticing the bug. I have now investigated the problem and found that it is a problem with Qwik. I have created an issue: https://github.com/BuilderIO/qwik/issues/3493
