### ISSUE TITLE
Return additional data from formAction$ (qwik)

### ISSUE THREAD

**Issue by tuurbo** [fabian-hiller/modular-forms#37]
Is there a way to return additional data from formAction$? Only status and message is returned.

```tsx
export const useFormAction = formAction$<SignupForm>(async (values, event) => {
  // create account and stuff

  return {
    status: 'success',
    message: 'Account created successfully!',
    data: {
      user: {
        id: 1,
        name: 'Bill',
      },
      cart: {
        quantity: 2,
      }
    },
  };
});

// component$
{signupForm.response.status === 'success' ? (
  <div>Thanks for signing up {signupForm.response.data.user.name}!</div>
) : (
  <SignupForm form={signupForm} />
)}
```

**Comment by fabian-hiller** [comment]
Not at the moment. Good idea, I'll think about it. Until then you could solve it with a local cache that you write in `formAction$` and read out in `routeLoader$`. Or ask in the Qwik Discord for a better solution.

**Comment by tuurbo** [comment]
Thanks :)

**Comment by fabian-hiller** [comment]
The new version is available. I have typed `data` so far only with `Record<string, any>`, but can improve this afterwards.

**Comment by tuurbo** [comment]
Thank you!
