### ISSUE TITLE
Circular reference when 'strict: true' in tsconfig.json

### ISSUE THREAD

**Issue by alexss3** [fabian-hiller/modular-forms#4]
I was getting the following error from Typescript when trying to build a basic form from the documentation in Typescript and SolidJS:

`Type of property 'prototype' circularly references itself in mapped type '{ [K in keyof Blob]-?: ValuePath<K & string, Blob[K]>; }'.ts(2615)`

I created a base project from the Stackblitz template, installed @modular-form/solid and set it up with the same eslint/tslint configuration as my main project.  I found I could get the error to go away in the sample project by removing "vitest/globals" from the "types" section of tsconfig.json, but this did not work for my main project.

The only thing I found that will cause the error to go away in my main project is to set "strict: false" in tsconfig.json.  Any ideas on a better solution to satisfy ts-lint but still have it set to strict mode?

**Comment by fabian-hiller** [comment]
That is interesting. I also have `strict` set to `true`. Even in the `tsconfig.js` of Modular Forms. Does [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) set to `true` help maybe? Otherwise, can you send me the link to the Stackblitz project?

**Comment by alexss3** [comment]
Adding `skipLibCheck: false` didn't change anything.  The Stackblitz I'm referring to is just based on the Solid/Typescript template from their front page, which I downloaded and added the other dependencies/config manually.  I could perhaps make a repo with just that if you like.

**Comment by fabian-hiller** [comment]
`false` is the default value. Please test it with `skipLibCheck: true`. Yes a repo would be helpful.

**Comment by alexss3** [comment]
Sorry, meant to say `true` when I wrote that.  In any case, I tried it with both `true/false` and neither worked.  Here is a repo of the sample project.  You should see the error in `App.tsx` and when you change `strict: true` in `tsconfig.json` the error should go away.
[https://github.com/alexss3/solid-modular-forms](https://github.com/alexss3/solid-modular-forms)

**Comment by alexss3** [comment]
Ok, I just tried it on my personal laptop and got the same error message.  I probably have a very similar setup with VS Code and could be the cause, though I'm not exactly sure what I should look for to find the root cause of it. 

On my laptop I disabled a couple extensions [Javascript and TypeScript Nightly, Prettier] and saw it go away, but can't reproduce the symptom to know which one it was.  On my other machine I tried the same and cannot get the error to go away at all, even after disabling all VS Code extensions.  Very strange indeed.

**Comment by fabian-hiller** [comment]
@alexss3 do you have any updates for me? Were you able to solve the problem?

**Comment by ikapo** [comment]
I am also encountering this problem, but on Emacs (using the vscode typescript LSP server though).
skipLibCheck: true is also enabled in my setup

**Comment by fabian-hiller** [comment]
I will look at the problem again. It's just difficult because I can't reproduce it properly.

**Comment by durandj** [comment]
I had the same issue and adding `"skipDefaultLibCheck": true` to my `tsconfig.json` fixed it for me. :man_shrugging:

**Comment by fabian-hiller** [comment]
I have made a few changes to the types and tried to solve the problem. Since I still can't reproduce it on my computer, I don't know if the changes were successful. Can you upgrade the library to v.0.8.3 and also upgrade TypeScript and check if it is solved. If TypeScript is installed globally, I also recommend updating the global version.

**Comment by durandj** [comment]
I updated to the latest version of Typescript and @modular-forms/solid and have `skipLibCheck` set to `true` and `skipDefaultLibCheck` set to `false` and the problem still exists.

I'll try and create a repo that reproduces the issue and add it to Github tomorrow.

**Comment by fabian-hiller** [comment]
After some investigation, I suspect that this is a problem that only exists with older TypeScript versions. The editors do not always use the version specified in package.json by default. In VS Code, for example, you can click "{}" in the status bar at the bottom of the screen to select the version. Can you check which version is shown there and if the error messages disappear when you upgrade to TypeScript v4.9.3?

**Comment by fabian-hiller** [comment]
@durandj for me, no error occurs when I clone your repository and install the npm packages.

**Comment by durandj** [comment]
Did you run `pnpm run lint`?

**Comment by fabian-hiller** [comment]
You are right, when running `pnpm run lint` the error occurred. I have found a way to reproduce the problem. When I click on "{}" in the status bar in VS Code, TypeScript v4.8.4 is displayed and no error occurs. If I switch to v4.9.3 I get the error. When I downgrade TypeScript with `pnpm i -D typescript@4.8.4` and then run `pnpm run lint` the error does not occur.

If it's due to the new TypeScript version, that also explains why the problem has only been occurring for a few days. In this case, I recommend downgrading to v4.8.4 until there is a solution to the problem.

**Comment by fabian-hiller** [comment]
I believe I have fixed the problem with v0.8.4 now. Although `File` extends `Blob`, it seems that TypeScript v4.9.3 no longer maps `T extends File` correctly. I have implemented a workaround for now.

**Comment by durandj** [comment]
The fix worked, thanks @fabian-hiller !

**Comment by ikapo** [comment]
Can confirm it fixed it for me as well. Thanks @fabian-hiller for the quick responses and a great library!

**Comment by fabian-hiller** [comment]
Thank you for your help!
