### ISSUE TITLE
previous two qwik update result in error

### ISSUE THREAD

**Issue by RBleyenberg** [fabian-hiller/modular-forms#45]
Think you need to update the deps tree of the library

```
npm i @modular-forms/qwik

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-qwik-basic-starter@undefined
npm ERR! Found: @builder.io/qwik@0.100.0
```

after running -force it's clear

```
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @modular-forms/qwik@0.5.0
npm WARN Found: @builder.io/qwik@0.100.0
npm WARN node_modules/@builder.io/qwik
npm WARN   peer @builder.io/qwik@">=0.22.0" from @builder.io/qwik-city@0.100.0
npm WARN   node_modules/@builder.io/qwik-city
npm WARN     dev @builder.io/qwik-city@"~0.100.0" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @builder.io/qwik@"^0.23.0" from @modular-forms/qwik@0.5.0
npm WARN node_modules/@modular-forms/qwik
npm WARN   @modular-forms/qwik@"*" from the root project
npm WARN
npm WARN Conflicting peer dependency: @builder.io/qwik@0.23.0
npm WARN node_modules/@builder.io/qwik
npm WARN   peer @builder.io/qwik@"^0.23.0" from @modular-forms/qwik@0.5.0
npm WARN   node_modules/@modular-forms/qwik
npm WARN     @modular-forms/qwik@"*" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @modular-forms/qwik@0.5.0
npm WARN Found: @builder.io/qwik-city@0.100.0
npm WARN node_modules/@builder.io/qwik-city
npm WARN   dev @builder.io/qwik-city@"~0.100.0" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @builder.io/qwik-city@"^0.6.5" from @modular-forms/qwik@0.5.0
npm WARN node_modules/@modular-forms/qwik
npm WARN   @modular-forms/qwik@"*" from the root project
npm WARN
npm WARN Conflicting peer dependency: @builder.io/qwik-city@0.6.6
npm WARN node_modules/@builder.io/qwik-city
npm WARN   peer @builder.io/qwik-city@"^0.6.5" from @modular-forms/qwik@0.5.0
npm WARN   node_modules/@modular-forms/qwik
npm WARN     @modular-forms/qwik@"*" from the root project
```

**Comment by fabian-hiller** [comment]
I will try to update the dependencies later.

**Comment by fabian-hiller** [comment]
The new version is now available.

**Comment by jmcelreavey** [comment]
I'm still getting this issue 🤔 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-qwik-basic-starter@undefined
npm ERR! Found: @builder.io/qwik@0.101.0
npm ERR! node_modules/@builder.io/qwik
npm ERR!   dev @builder.io/qwik@"^0.101.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @builder.io/qwik@"^0.23.0" from @modular-forms/qwik@0.7.0
npm ERR! node_modules/@modular-forms/qwik
npm ERR!   @modular-forms/qwik@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/john/.npm/_logs/2023-04-06T20_18_48_202Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2023-04-06T20_18_48_202Z-debug-0.log

**Comment by fabian-hiller** [comment]
I suspect that as has to do with the peer dependencies specification in our package.json. I'll update this in the next hour.

**Comment by jmcelreavey** [comment]
Pushed an MR for this to save you any hassle: https://github.com/fabian-hiller/modular-forms/pull/49

**Comment by jmcelreavey** [comment]
Not sure what your process is but I pointed the MR towards develop.
