### ISSUE TITLE
onSubmit event does not require event.preventDefault()

### ISSUE THREAD

**Issue by Excelsior2021** [fabian-hiller/modular-forms#47]
Hi,

Great library. I am experimenting with the library and noticed that if I use event.preventDefault() in my submit handler for the form, the handler does not execute. Only if I remove event.preventDefault() does the handler execute. I also notice that the browser does not refresh without event.preventDefault. I pressume this was intentional. It would be nice to have that in the documentation.

Thanks again for putting together such a great library, it's very useful!

**Comment by fabian-hiller** [comment]
Do you use SolidJS or Qwik? If you follow the documentation, you don't need to run `event.preventDefault()` at all, because Modular Forms does that for you. `event.preventDefault()` prevents the page from reloading on submission.

**Comment by Excelsior2021** [comment]
Hi Fabian,

I am using SolidJS. I understand. I would suggest adding to the documentation that "event.preventDefault() is not required", because it's is not stated and it might confuse others.

**Comment by fabian-hiller** [comment]
Good idea and thanks for your feedback! I will update this. Feel free to contact me anytime if you notice more things. Soon there will be a big update for the SolidJS version, where I will improve a lot of things.
