### ISSUE TITLE
formAction$ unknown errors should be logged or propagated

### ISSUE THREAD

**Issue by juanpmarin** [fabian-hiller/modular-forms#50]
Unknown errors that occur inside a `formAction` are being returned to the client but do not generate error logs, that's dangerous because unknown errors cannot be monitored on the backend side, as they do not generate any logs. Making it challenging to spot new bugs

https://github.com/fabian-hiller/modular-forms/blob/43c304c3602e86f92c3d1aeedb0683257abb364b/packages/qwik/src/actions/formAction%24.ts#L106-L113

**Comment by fabian-hiller** [comment]
You are right, we could add `console.error(error)` to make the error show up in the server logs. Did you read the "[Throw and display errors](https://modularforms.dev/guides/handle-submission)" part in the documentation? There you can learn more about error handling.

**Comment by juanpmarin** [comment]
Yes! I did, and I understand that I would manually catch unexpected errors in places where they can occur but I think it's a dangerous default behavior because you depend on the developer to catch those errors, I think it would be safer to log unexpected errors by default and manually catch those that you want to handle differently 

What do you think?

**Comment by fabian-hiller** [comment]
Do I understand you correctly that you would keep the default error message for unknown errors to not accidentally send secret data to the client, but add a `console.error(error)` statement to the implementation so that the error appears in the server logs and can be investigated afterwards?

```ts
try {
  …
} catch (error: any) {
  console.error(error); // This line is new
  formActionStore.response = { 
    status: 'error', 
    message: 'An unknown error has occurred.', 
  }; 
} 
```

**Comment by juanpmarin** [comment]
That's right :D 
Although I don't know what logging mechanism qwik uses, so I'm not sure if `console.error` is the right choice

**Comment by fabian-hiller** [comment]
I will find out and then improve the code. Thanks a lot for your hint!

**Comment by fabian-hiller** [comment]
I have added the log statement.
