### ISSUE TITLE
dirty check when setting data from routeLoader

### ISSUE THREAD

**Issue by RBleyenberg** [fabian-hiller/modular-forms#52]
Hello,

I have the following;

```

export const useRouteLoaderFormCountry = routeLoader$<InitialValues<TCrmCountry>>(() => ({
    id: '',
    code: '',
    name: ''
}));


    useTask$(() => {
        console.log(countryForm.dirty)
        if (_useRouteLoaderCountry && _useRouteLoaderCountry.id !== '') {
            setValue(countryForm, 'id', _useRouteLoaderCountry?.id);
            setValue(countryForm, 'code', _useRouteLoaderCountry.code);
            setValue(countryForm, 'name', _useRouteLoaderCountry.name);
            console.log(countryForm.dirty)
        }
    })

    //FORM INPUT TRANSFORM
    useTask$(({ track }) => {
        console.log(countryForm.dirty)
        const code = track(() => getValue(countryForm, 'code')?.trim())
        const name = track(() => getValue(countryForm, 'name')?.trim())
        if (code) {
            setValue(countryForm, 'code', code.toUpperCase())
        }
        if (name) {
            const capitalized = name.charAt(0).toUpperCase() + name.slice(1)
            setValue(countryForm, 'name', capitalized)
        }
        console.log(countryForm.dirty)
    })
```

So we get a country from a the routeLoader and we trying to have the save button disabled with a css class 

`${!countryForm.dirty ? 'disabled' : null}`

but on all the console.log values the dirty is true which make sence but if we replace those with  

`  countryForm.dirty = false;`

so we can start the filled form with a dirty of false, it just stays true.

Are we overlooking something simple again... 

Thanks for you time

**Comment by fabian-hiller** [comment]
Can you reproduce the problem for me in a [Stackblitz project](https://qwik.new) and tell me exactly what the current behavior is and what behavior you would actually expect. Then I can take a close look at the problem.

Then another hint: To set several values at once, you can now use [`setValues`](https://modularforms.dev/api/setValues).

**Comment by fabian-hiller** [comment]
It is intended that `setValue` and `setValues` set `form.dirty` to `true` if the new value is not equal to the initial value.

Are you trying to use `setValues` in `useTask$` to set the initial values of the form? If so, why don't you use `loader: useFormLoader()` as explained [here](https://modularforms.dev/guides/create-your-form)? If you want to set initial values afterwards, you should use [`reset`](https://modularforms.dev/api/reset) for that.

**Comment by fabian-hiller** [comment]
If you want to apply the transformation in `useTask$` only if the field is dirty, you can use the `shouldDirty` option of [`getValue`](https://modularforms.dev/api/getValue) to return only dirty values.

**Comment by RBleyenberg** [comment]
awesome both solutions work;

Forgot about the useFormLoader so easy fix on the whole dirty case ^^
and the options on getValue, setValues ect. we didn't notice before

Thanks a bunch.
