### ISSUE TITLE
Up to date documentation for Solid?

### ISSUE THREAD

**Issue by jmcelreavey** [fabian-hiller/modular-forms#55]
Hey 👋 

I'm following through on your solid guide, specifically this [page](https://modularforms.dev/solid/guides/handle-submission) though it seems outdated.

There's no action property available on the `Form` and `onSubmit()` now seems to be required? I had assumed I somehow have to call my server function `loggingInAction` i.e `const [loggingIn, loggingInAction] = createServerAction$(...)` from the `onSubmit` now but I can't seem to see how?

Thanks in advance

**Comment by fabian-hiller** [comment]
Hey, actions are not yet implemented for SolidJS, as mentioned on the page. You can read more about it here: https://github.com/fabian-hiller/modular-forms/issues/3#issuecomment-1512877615
