### ISSUE TITLE
Require validation for formAction$

### ISSUE THREAD

**Issue by wmertens** [fabian-hiller/modular-forms#57]
Since anybody can send anything, it seems like a security issue to not require validation.

**Comment by fabian-hiller** [comment]
Thank you very much for creating this issue. I actually agree with you there, but have not required it so far, as Qwik does not do that with `routeAction$` either. However, validation is an important part of Modular Forms and enforcing it could help avoid security issues in production. I would like to wait for further feedback here before making a decision.

**Comment by fabian-hiller** [comment]
Hey, I would like to give an update on this. I like your idea and think I will make validation required server-side before Modular Forms goes into v1.

**Comment by fabian-hiller** [comment]
Starting with the next version, validation will be required when using `formAction$`.
