### ISSUE TITLE
Response object TypeScript

### ISSUE THREAD

**Issue by susickypavel** [fabian-hiller/modular-forms#6]
Hi (me again) 👋,

I've got more of a question than an issue. I find the [response](https://modularforms.dev/api/Response) property on the form handy. However, its type feels somewhat cumbersome as it is a union type of `{ status: string, message: string }` and empty object, and it's a must to narrow the type, which can become kinda wordy in large forms and it also feels like work that doesn't need to be done. Also, the individual types such as `ResponseObject` or the mentioned anonymous object aren't exported from the lib, so they need to be redeclared on the user's side when using them for type narrowing.

I'm wondering whether it is a good idea to leave it up to the consumer the type and initial value of the response object? I'd probably find it more useful that way; at the very least, exporting the mentioned types would help a ton.

**Comment by fabian-hiller** [comment]
Hey, thanks for your feedback! I don't really understand what I could do better. Maybe it will help me if you show me your code. Modular Forms does not force you to use the `response` property. You can catch and handle errors on your own.

The `Response` type is exported from the library. I use it for example to create my own `FormResponse` component, to which I can simply pass the `response` property.

```tsx
// components/FormResponse.tsx
import clsx from 'clsx';
import { Response } from '@modular-forms/solid';
import { Expandable } from './Expandable';

type FormResponseProps = Response & {
  class?: string;
};

export function FormResponse(props: FormResponseProps) {
  return (
    <Expandable expanded={!!props.message}>
      <div
        class={clsx(
          'px-8 md:text-lg lg:px-10 lg:text-xl',
          props.status === 'success' &&
            'text-emerald-500 dark:text-emerald-400',
          props.status === 'error' && 'text-red-500 dark:text-red-400',
          props.class
        )}
      >
        {props.message}
      </div>
    </Expandable>
  );
}

// routes/login.tsx
import { createForm, Field, Form } from '@modular-forms/solid';
import { FormResponse } from '~/components';

type LoginForm = {
  email: string;
  password: string;
};

export default function LoginPage() {
  const loginForm = createForm<LoginForm>();
  return (
    <Form of={loginForm} onSubmit={...}>
      <Field of={loginForm} name="email">
        {(field) => <input {...field.props} type="email" />}
      </Field>
      <Field of={loginForm} name="password">
        {(field) => <input {...field.props} type="password" />}
      </Field>
      <FormResponse {...loginForm.response} />
      <input type="submit" />
    </Form>
  );
}
```

**Comment by susickypavel** [comment]
I'm sorry I didn't describe the issue thoroughly. I'll try to do better this time. 

I've tried the example, and I still see the same issue. TypeScript complains about `props.status` or `props.message` because it can be an empty object (when no response was created or it was cleared), but it can also be the response object.
This is because of the union type. 

```
Property 'message' does not exist on type 'FormResponseProps'.
  Property 'message' does not exist on type '{ class?: string; }'
```

```ts
type Response = {
    status: ResponseStatus;
    message: string;
} | {};
```

If I'd delete the `| {}`, it would start to work because now TypeScript knows for sure this object will always look like this, but that might not be the case when the form wasn't submitted, or it was cleared.

So to satisfy the compiler I must do typechecking whether the properties do exist on the response object.

Maybe making the object Partial instead of the union could be a better experience?

```
type Response = Partial<{
    status: ResponseStatus;
    message: string;
}>
```

Then I can easily inline the `chaining operator`, `or` or `nullish coalescing operator` to handle the missing properties.

---

Maybe there is something I'm missing on in TypeScript, and it isn't the fault of this library, so take my advice above with a grain of salt :D

**Comment by fabian-hiller** [comment]
Now I understand what you mean. I had implemented it that way at the time to make sure `status` and `message` were present, or neither. So that it is clear that one cannot exist without the other. I realize, however, that this makes your code more cumbersome. Currently I tend to implement your suggestion and use `Partial`.

**Comment by fabian-hiller** [comment]
v0.9.1 is now online. I have changed the `Response` type as suggested. Thanks for your feedback!
