### ISSUE TITLE
Adding a fieldarray field with insert() doesn't update form value.

### ISSUE THREAD

**Issue by kieran-mgc** [fabian-hiller/modular-forms#60]
You can see the issue at https://modularforms.dev/solid/playground/todos

If you click "Add new", the value isn't updated in the sidebar, nor does it update when you input text into the fields.

Once you edit one of the other fields or use move() it will start working properly.

For now i'm getting around this by changing my add function to

```
const add = () => {
   insert(todoForm, 'todos', {
       value: { label: '', deadline: '' },
   });
   move(todoForm, 'todos', { from: 0, to: 1 });
   move(todoForm, 'todos', { from: 0, to: 1 });
}
```

**Comment by fabian-hiller** [comment]
Thank you very much for your attention. I will fix this as soon as possible.

**Comment by fabian-hiller** [comment]
Problem was that only a listener was set on the read fields. However, not on newly added fields or array items. The problem should be fixed with the new version that will be released soon.

**Comment by kieran-mgc** [comment]
Awesome! Thanks for the quick response
