### ISSUE TITLE
With multiple forms on one page, both call the same formAction$

### ISSUE THREAD

**Issue by jamiev-dfm** [fabian-hiller/modular-forms#62]
I have a login and register form in two different tabs on the same page, and I'm passing a different action to each of them, but both of them call the register action when they're submitted.

If I edit the login action while the development server is running, then both forms start to call that one instead.

**Comment by fabian-hiller** [comment]
Can you send me your code here or make it available via GitHub or StackBlitz?

**Comment by jamiev-dfm** [comment]
Here's a minimal example: https://github.com/jamiev-dfm/multiple-forms-example/blob/master/src/components/starter/hero/hero.tsx

If you run that, both forms log "Form 2 submitted" when you submit them.

**Comment by fabian-hiller** [comment]
Thank you for the code example. I will investigate it.

**Comment by fabian-hiller** [comment]
Thank you for your attention. I think I have solved the problem and will release a new version in a few minutes.
