### ISSUE TITLE
Latest version doesn't work with latest solid

### ISSUE THREAD

**Issue by marcusbuffett** [fabian-hiller/modular-forms#68]
I'm getting an error about memo not being exported from "solid-js/web"
<img width="1035" alt="CleanShot 2023-05-13 at 21 20 19@2x" src="https://github.com/fabian-hiller/modular-forms/assets/1834328/2e037db9-5a60-4c63-af42-9ff8ae194580">

**Comment by fabian-hiller** [comment]
Thank you very much for pointing this out. I will update SolidJS and investigate the problem.

**Comment by fabian-hiller** [comment]
`memo` is not part of the Modular Forms source code, but was added automatically during the build step. `memo` is part of [`dom-expressions`](https://github.com/ryansolid/dom-expressions) and is exported in v1.7.5 from `solid-js/web`. If the problem persists, I need a sample repository or StackBlitz project to investigate.

**Comment by marcusbuffett** [comment]
Oh huh this must have just been a weird thing on my side, clearing out node_modules fixed it, sorry for the false report
