### ISSUE TITLE
Form Loader with default values for checkbox

### ISSUE THREAD

**Issue by Djay77** [fabian-hiller/modular-forms#70]
Hello,

I tried to precheck some checkbox in my modularForm with Qwik.
But I have an error message when I add some initial data : **Blob is not defined**

<img width="1100" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/3582550/1b24421d-98f6-4641-b04c-7fd2c66ba022">

<img width="671" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/3582550/c3162508-d55b-406d-a2b8-fd02bc47e6e5">

<img width="793" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/3582550/48ca22b2-bcde-46af-b9c3-24f1d16cdef2">

---
Qwik/City 1.1.0
@modular-forms/qwik 0.13.0
---

To test, I tried to integrate checkboxes from https://stackblitz.com/edit/modular-forms-qwik?file=src%2Froutes%2Fspecial%2Findex.tsx and I have the same error.

Something changed with the lastest versions ?

Thanks you

**Comment by fabian-hiller** [comment]
For me it works without problems. With the new version as well as with v0.13.0. I have tested it in StackBlitz and in my local environment. If the problem persists for you, please provide me with a StackBlitz project or code I can copy so I can investigate it better.
