### ISSUE TITLE
Handle multiple input type text with same name ?

### ISSUE THREAD

**Issue by Djay77** [fabian-hiller/modular-forms#71]
Hello,

Is it possible to handle this kind of payload ? (multiples inputs text (not checkbox))
<img width="171" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/3582550/b3efe93d-6748-4cdd-a8ec-6b5b7a2c3a8f">

I tried with string[] but without success
<img width="570" alt="image" src="https://github.com/fabian-hiller/modular-forms/assets/3582550/1a8a34f4-05ba-4299-8710-c81a80854b8c">

My values in formAction$ are still empty

Thanks you

**Comment by fabian-hiller** [comment]
If not, please provide me more example code.

**Comment by fabian-hiller** [comment]
Were you able to solve your problem with the guides? If yes, I would close the issue.
