### ISSUE TITLE
Is there a way to print all errors? 

### ISSUE THREAD

**Issue by teenjuna** [fabian-hiller/modular-forms#72]
Right now I only see `getError` for getting error for individual field. Having a function like `getErrors` for getting all errors would be very useful for debugging.

**Comment by fabian-hiller** [comment]
That's right. I will probably do the implementation for it tomorrow.

**Comment by teenjuna** [comment]
It actually returns empty string for all of my errors. I thought it's a design decision.

**Comment by fabian-hiller** [comment]
@mattbdc so far no problems have been encountered with this approach. Can you make a practical code example where this procedure is a problem?

**Comment by teenjuna** [comment]
Fabian, wrt the return type I'm voting for the object. With the Zod schema, I often have similar errors for different fields (like value is required), and with array I wouldn't be able to understand the cause of the error.

RE nested arrays, I would be fine with keys like `arrayfield.0`, `arrayfield.0.other_field`. This is mostly for debugging, so it's fine

**Comment by fabian-hiller** [comment]
Until I implement the method, you can fall back to the following code:

```ts
import { FieldValues, FormStore, ResponseData } from '@modular-forms/solid';

function getErrors<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData
>(form: FormStore<TFieldValues, TResponseData>) {
  return Object.entries({
    ...form.internal.fields,
    ...form.internal.fieldArrays,
  }).reduce<Record<string, string>>((formErrors, [name, store]: any) => {
    if (store?.error.get()) {
      formErrors[name] = store?.error.get();
    }
    return formErrors;
  }, {});
}

```

**Comment by fabian-hiller** [comment]
`getErrors` is now available: https://modularforms.dev/solid/api/getErrors

**Comment by teenjuna** [comment]
Yay, Fabian, thank you!

**Comment by fabian-hiller** [comment]
Do you recommend returning the error message or an empty string otherwise?

**Comment by fabian-hiller** [comment]
Currently `field.error` is always a string when using the `Field` component. I am not sure anymore if this had a specific reason. In practice at least there were no problems with this approach yet. In the long run I will think about whether `undefined` would be better.

```tsx
<Field
  name="email"
  validate={[
    required('Please enter your email.'),
    email('The email address is badly formatted.'),
  ]}
>
  {(field, props) => (
    <>
      <input {...props} type="email" required />
      {field.error && <div>{field.error}</div>}
    </>
  )}
</Field>
```
