### ISSUE TITLE
Dynamically rendering inputs causes validation to always return false

### ISSUE THREAD

**Issue by kseikyo** [fabian-hiller/modular-forms#73]
As discussed on discord, I got a more minimal reproduction of both issues in a sandbox. It's using astro to be more closely related to my actual environment.

https://dub.sh/XMsdjBH

Just adding the comment from @fabian-hiller 

> I think that the bug is in line 117. Here valid is set to false if at least one error was found when validating the schema. Since schema validation always validates the entire schema, in your case validate is always set to false. However, this should only happen if an error applies to an selected field. I need to check this more closely though. https://github.com/fabian-hiller/modular-forms/blob/main/packages/solid/src/methods/validate.ts#L117

**Comment by fabian-hiller** [comment]
Thank you very much! I will investigate the problem as soon as possible (probably today or tomorrow) and find a solution.

**Comment by kseikyo** [comment]
Awesome, let me know if I can help in any way.

**Comment by fabian-hiller** [comment]
The bug should be fixed in the new version. Feel free to contact me if you have further problems.
