### ISSUE TITLE
Errors getting triggered when inputs are dynamically rendered 

### ISSUE THREAD

**Issue by kseikyo** [fabian-hiller/modular-forms#74]
Errors are showing in the UI when new inputs are rendered without any interaction.

See comments in lines 92 and 97.
 
Related to #73
https://dub.sh/XMsdjBH

**Comment by fabian-hiller** [comment]
Thank you! I will check that later.

**Comment by fabian-hiller** [comment]
A `<button />` inside a `<form />` element, submits the form automatically on click and this triggers the validation of the whole form. By adding the `type` attribute with the value `button` to your button, you can change this behavior. Feel free to contact me if you have any further questions.
