### ISSUE TITLE
ModularForm documentation example for Qwik useComputed$ does not work { track } is not a valid argument

### ISSUE THREAD

**Issue by og-dev** [fabian-hiller/modular-forms#76]
```typescript 
import { component$, useComputed$, … } from '@builder.io/qwik';

type DateInputProps = { … };

export const DateInput = component$(({ value, ...props }: DateInputProps) => {
  // Transform date or number to string
  const input = useComputed$(({ track }) =>
    track(() => value) &&
    !Number.isNaN(typeof value === "number" ? value : value.getTime())
      ? new Date(value).toISOString().split("T", 1)[0]
      : undefined
  );
  return <input {...props} type="date" value={input.value} />;
});
```
Error:
`Argument of type '({ track }: { track: any; }) => string | undefined' is not assignable to parameter of type 'ComputedFn<string | undefined>'`

I'm using Qwik 1.1.4 with modular-form 0.14

I am trying to modify the value of an input dynamically, but the new  generated value is not sent with the form. It always sends the last typed value , not the dynamically generated value.

**Comment by fabian-hiller** [comment]
Can you provide me a reproduction e.g. via StackBlitz and steps how to reproduce the bug? You can use this as a starting point: https://stackblitz.com/edit/modular-forms-qwik

**Comment by fabian-hiller** [comment]
Does the problem still exist or were you able to solve it?

**Comment by og-dev** [comment]
> Does the problem still exist or were you able to solve it?

yes, problem still exist.

Please go to:
https://stackblitz.com/edit/modular-forms-qwik-qhds3v?file=src%2Froutes%2Fdate%2Findex.tsx

this project compiles if you comment or delete input const and change the value of the input to value(props.value)

**Comment by fabian-hiller** [comment]
I think that `useComputed$` has no `track`. It tracks it dependencies automatically. See: https://qwik.builder.io/docs/components/state/#usecomputed
