### ISSUE TITLE
 Key "active" in a Field component always "true".  Question

### ISSUE THREAD

**Issue by igorro79** [fabian-hiller/modular-forms#77]
I'm trying to decorate a label element when the field is active. To do this, I need to know the current state of the input field (focused/active or not active). i am trying to use **field.active** value. but it is always **true** whether the field is active or not. I tried to explicitly set the keepActive value to false - the same result.

**Comment by fabian-hiller** [comment]
`field.active` tells if the element is in the DOM and is mainly used internally. What you have in mind, I would try to solve with CSS selectors. You can do that independently from Modular Forms.

**Comment by fabian-hiller** [comment]
Were you able to solve the problem or do you have further questions? Otherwise, I would close the issue.

**Comment by igorro79** [comment]
Yes, problem solved. Thanks for answering.
