### ISSUE TITLE
Feature request: Virtual fields.

### ISSUE THREAD

**Issue by NikolaRHristov** [fabian-hiller/modular-forms#80]
Support for hidden fields. When you have a field that's not visible or `type="hidden"` the validator does not pick it up.

**Comment by NikolaRHristov** [comment]
I believe this is due to the element losing focus.

**Comment by NikolaRHristov** [comment]
I resolved this by triggering the input event on the hidden element.

**Comment by fabian-hiller** [comment]
Can you provide me here, via StackBlitz or a GitHub repository sample code of a form with a hidden field and describe what I have to do for the problem to occur? Then I will investigate the problem.

**Comment by NikolaRHristov** [comment]
Yeah sure.

**Comment by NikolaRHristov** [comment]
You can see the example here. https://github.com/NikolaRHristov/solidjs-templates-5kg4bx

Basically, what I want is a sort of a virtual field that can be validated through the normal validation even though it's hidden. You can see line https://github.com/NikolaRHristov/solidjs-templates-5kg4bx/blob/main/src/App.tsx#L98

**Comment by NikolaRHristov** [comment]
It may be impossible. Again, I just workaround that with `createEffect` and it works!

**Comment by NikolaRHristov** [comment]
```ts
id={fieldId}
```

is the hotfix.

**Comment by NikolaRHristov** [comment]
Actually I can accomplish this with the `validate` function inside a `createEffect`. Thank you! You've been most helpful!

**Comment by NikolaRHristov** [comment]
Also, this library is awesome!

**Comment by NikolaRHristov** [comment]
Yeah, just did that.

```ts
	monacoEditor.getModel()?.onDidChangeContent(() => {
		_setValue(monacoEditor.getModel()?.getValue() ?? "");
	});

	createEffect(
		on(
			value,
			(value) => {
				monacoEditor.getModel()?.setValue(value);
				setValue(editForm, "content", value);
			},
			{ defer: true }
		)
	);
```
