### ISSUE TITLE
type issue when setting `initialValues` using `reset`

### ISSUE THREAD

**Issue by ghalle** [fabian-hiller/modular-forms#81]
Trying to call `reset` with a form of type `T` and `inittialValues` set to a value of type `PartialValues<T>` will cause a hard to decipher typescript error.

The type of `initialValues` should be `PartialValues<TFieldValues>`  so there shouldn't be an error, but typescript uses the type of `initialValues` to contribute to the inference of `TFieldValues` creating an issue with the types.

Commenting out the 2 other variants of `reset` in `reset.d.ts` in an application using the built version of modular-forms shows a clearer error:

 <details>
  <summary>Error</summary>

> Argument of type 'FormStore<{ name: string; portrayedBy: string; gender: string; age: string; race: string; hair: { length: string; type: string; color: string; }; boobs: string; tags: string[]; }, undefined>' is not assignable to parameter of type 'FormStore<{ name?: Maybe<string>; portrayedBy?: Maybe<string>; gender?: Maybe<string>; age?: Maybe<string>; race?: Maybe<string>; hair?: { length?: Maybe<string>; type?: Maybe<...>; color?: Maybe<...>; } | undefined; boobs?: Maybe<...>; tags?: string[] | undefined; }, undefined>'.

</details>

Modifying `ResetOptions` in `reset.d.ts` to use `NoInfer` fixes the issue:
<details>
  <summary>Modified ResetOptions</summary>

```typescript
type NoInfer<T> = [T][T extends any ? 0 : never]

/**
 * Value type of the reset options.
 */
export type ResetOptions<TFieldValues extends FieldValues, TFieldName extends FieldPath<TFieldValues>> = Partial<{
    initialValue: FieldPathValue<TFieldValues, TFieldName>;
    initialValues: PartialValues<TFieldValues>;
    keepResponse: boolean;
    keepSubmitCount: boolean;
    keepSubmitted: boolean;
    keepValues: boolean;
    keepDirtyValues: boolean;
    keepItems: boolean;
    keepDirtyItems: boolean;
    keepErrors: boolean;
    keepTouched: boolean;
    keepDirty: boolean;
}>;
```
</details>

Trying to update the source to use the new type above however causes some issue with the internal types of the library:
<details>
  <summary>Screenshot</summary>
  
![Code_kFvm6fWYZV](https://github.com/fabian-hiller/modular-forms/assets/2764750/abdbe56e-ccc5-43b6-b65d-ef6c2906705e)

</details>

I'm not sure how to fix this issue without causing further issues with the internal types, hopefully someone else can figure it out.

Here's an example of the issue in typescript playground:
[Example](https://tsplay.dev/wXrBQm)

**Comment by fabian-hiller** [comment]
If a generic is used, it seems to work. Maybe this will help as a workaround until I have a closer look at the problem: https://tsplay.dev/Nr9V2w

```ts
function openWithGeneric<TValues extends PartialValues<CharacterForm>>(
  character: TValues,
) {
  reset(characterForm, {
    initialValues: character,
  })
}
```

**Comment by fabian-hiller** [comment]
I am not sure why the problem exists and if I can do anything about it. Since the workaround using a generic solves the problem, I am closing the issue. However, I am willing to reopen it if more people come across it and the current workaround is too cumbersome.
