### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by corbolt** [fabian-hiller/modular-forms#82]
I just tried to import your lib into one of my projects, but webpack fails with this error message:

`ERROR in ./node_modules/@modular-forms/solid/dist/esm/index.js 353:54
    Module parse failed: Unexpected token (353:54)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    | 
    | function getPathValue(path, object) {
    >   return path.split('.').reduce((value, key) => value?.[key], object);
    | }
    | `

i have no clue what i need to do to fix this. any help would be highly appreciated.

**Comment by fabian-hiller** [comment]
Hey, sorry, I'm not familiar with Webpack. Is there a reason why you use Webpack instead of Vite with Rollup? I use the community package `rollup-preset-solid` to build my library, which is also used by many other projects. I have no direct influence on the output.

**Comment by fabian-hiller** [comment]
Seems that your Webpack configuration can't handle "modern" JavaScript with the `?.` syntax. Probably this can be configured though.

**Comment by corbolt** [comment]
thanks, fabian. yes, probably a miss-config on webpack - ill update, if i can find a solution for this one.

**Comment by fabian-hiller** [comment]
I am closing this issue. If you have found a solution or there is a reason to reopen the issue, please let me know via a comment.
