### ISSUE TITLE
The value of radio buttons is always the first option when no options selected

### ISSUE THREAD

**Issue by devange** [fabian-hiller/modular-forms#83]
When there is a **radio** button in the form but none of the options are selected, the value of the radio in the onSubmit data is always the first option's value, and does not trigger a validation error, even when I disable the first option.
Here is an [example](https://stackblitz.com/edit/modular-forms-solid-ubsrh8?file=src%2Froutes%2Fspecial.tsx) modified from the official playground.
I am using the SolidJS version.

**Comment by fabian-hiller** [comment]
I have released a new version. Can you check if it works now?

**Comment by devange** [comment]
> I have released a new version. Can you check if it works now?

Yes, it's resolved now, thank you.

**Comment by fabian-hiller** [comment]
Thank you for mentioning the issue!
