### ISSUE TITLE
error when posting from that has an image with formAction$.

### ISSUE THREAD

**Issue by robertwach** [fabian-hiller/modular-forms#90]
Internal server error: Value cannot be serialized in _.values.image  because it's an instance of "File"

 You might need to use 'noSerialize()' or use an object literal instead.

**Comment by robertwach** [comment]
![image](https://github.com/fabian-hiller/modular-forms/assets/16592278/e0a33e23-a7b1-4164-8b0c-ad16c4a6f3e4)
Server-side validation

![image](https://github.com/fabian-hiller/modular-forms/assets/16592278/8d96a0f6-e23b-4f0e-8f5e-d92392e5e989)
from validation schema

the issues still remains  error Trying to serialize Blob { size: 44381, type: 'image/jpeg' }

**Comment by robertwach** [comment]
Found the error. Added name attribute to input field and Field element![image](https://github.com/fabian-hiller/modular-forms/assets/16592278/e8fc197d-a396-4642-8d5e-2899f83c0473)


Appreciated the help

**Comment by fabian-hiller** [comment]
Mhm... `name` should be already in `props`. The special form in this example includes a file uploads that works on my maschiene (StackBlitz does not support actions yet): https://stackblitz.com/edit/modular-forms-qwik-actions
