### ISSUE TITLE
Novalidate can't be overridden (SolidJS)

### ISSUE THREAD

**Issue by susickypavel** [fabian-hiller/modular-forms#92]
Form component sets `novalidate="true"` by default and can't be overridden. I want to create progressively enhanced forms with native HTML validation, but it can't be done this way.

**Comment by fabian-hiller** [comment]
Modular forms currently only support progressively enhanced forms in Qwik. For SolidJS we are waiting for changes in SolidStart so that we can implement it with a good DX.

What advantage do you have with Modulars Forms if you use HTML validation? If it makes sense, I can modify the `Form` component to allow the attribute to be overridden.

**Comment by susickypavel** [comment]
I've been using Modular forms with Astro (for quite some time and didn't see many issues, btw). If I can override the novalidate attribute, I can set it to false by default then the form will be validated by native HTML validation, so I can give user at least some minimal validation without js because the form will be SSR-ed. If the user has scripting available/enabled, I can set the novalidate to false on mount and use modular forms as usual.

**Comment by fabian-hiller** [comment]
I understand. That makes sense. I will try to improve that tomorrow.

**Comment by fabian-hiller** [comment]
Apart from that, do you have any other ideas for improving the API? Will be working on Modular Forms next week to get to v1 in the next few months.

**Comment by susickypavel** [comment]
> Apart from that, do you have any other ideas for improving the API? Will be working on Modular Forms next week to get to v1 in the next few months.

I think the API is very well written. it's intuitive and robust. I had only a few issues that you quickly fixed or helped me with.

One thing that I quite often came across was "duplicating" of validation and validation attributes. Let's see example below.

```tsx
<Field
	name="Name"
	validate={[
		required("Please enter your name"),
		minLength(2, "Name should be at least 2 characters long"),
		maxLength(50, "Name should be at most 50 characters long"),
	]}
	>
	{(field, props) => (
		<input
			{...props} 
			required
			minLength={2}
			maxLength={50}
		/>
	)}
</Field>
```

It might be useful to automatically populate `props` with `minLength`, `maxLength` and `required` attributes if matching counterpart in `validate` prop are passed. However, it might be up to discussion because even with `novalidate="true"` the maxLength constraints the maximum number of characters input can have so it might break some very exotic usage of inputs. On the other hand, the developer can split the props and don't pass it to the input if it breaks their usage.

There would be two benefits:

1. You don't "duplicate" the validation logic.
2. It improves the accessibility of most forms without the need for some developer intervention.

---

Another thing that caught my eye is that the `Form` component is rendered with `of` attribute with value `[object Object]` which doesn't seem correct or even useful, so maybe it's accidentally passed?

--- 

Lastly, it's very common to create ids for inputs and error elements to associate them with correct labels and error texts. It might be helpful to add some string identification of the form that can be used to distinguish the same inputs between different forms (on the same page) so you can reduce the change of id collision.

**Comment by fabian-hiller** [comment]
Thanks a lot for your feedback! I fixed the `noValidate` problem. I'll look at the other things on Monday.

**Comment by susickypavel** [comment]
I tried the fix and realized I misunderstood how `novalidate` works. The `novalidate` is a boolean attribute. Based on the [HTML spec](https://html.spec.whatwg.org/dev/form-control-infrastructure.html#attr-fs-novalidate), to represent a "true" value, the attribute must be present (as it is by default) and if the value should be `false` then the attribute must be omitted altogether.

 The attribute is present by default, so we need to pass `null` to the form to remove it.
 
 ```tsx
 <Form onSubmit={onSubmit} noValidate={null}>
...
</Form>
 ```

However, TypeScript accepts `boolean` so it throws a type error.

```
Type null is not assignable to type boolean.
```

**Comment by fabian-hiller** [comment]
Won't the attribute be removed if you set the value to `false`?

**Comment by susickypavel** [comment]
Not quite, there are attributes that needs false to be on the element (aria-expanded for example). Maybe it's browser specific or even framework SSR specific.

**Comment by susickypavel** [comment]
Okay, I think I finally understand what's going on. A similar issue is with `autoFocus` in the field props.

There is a difference between `novalidate` and `noValidate`, `autofocus` and `autoFocus`.

`novalidate`, `autofocus` (lowercase) are valid HTML attributes, but `noValidate` and `autoFocus` aren't, they are just "convenient" wrappers for developers that _should_ map to native HTML attributes. However, for some reason Solid (at least with conjunction with Astro) doesn't map it and renders it as is, hence in the HTML is `autoFocus="false"` which translates for HTML as `autofocus=""`

Solution is to rename `noValidate` to `novalidate` and `autoFocus` to `autofocus`.

EDIT: Maybe the camelCase props aren't even valid at all, in Solid playground it throws a type error.

**Comment by susickypavel** [comment]
@fabian-hiller I created a PR to fix this (changed it only for the SolidJS package as I don't know if other libraries suffer by this). It's just a rename, and it seems to be fixing all the issues above.

**Comment by fabian-hiller** [comment]
The issue should be fixed in the new version.

**Comment by fabian-hiller** [comment]
> I think the API is very well written. it's intuitive and robust. I had only a few issues that you quickly fixed or helped me with.

@susickypavel thank you for your feedback! Can you create an issue for each suggestion? Especially the `of` property I would like to fix in a timely manner. Thank you very much for the hint.

**Comment by fabian-hiller** [comment]
> Lastly, it's very common to create ids...

Can you also create a issue for this improvement. I find this interesting and an implementation also seems quite simple.
