### ISSUE TITLE
[Question] React to changes in an ArrayField

### ISSUE THREAD

**Issue by whytspace** [fabian-hiller/modular-forms#93]
I am trying to improve user experience by not requiring the user to actively "create new entries". there should always be one _empty_ entry in the ArrayField _waiting_ for some data input.

I was thinking of implementing this behaviour by listening to changes on the ArrayField, checking if there is still an empty entry, and use the `insert` function when not.

But it seems that I cannot subscribe to changes in ArrayField values, only on individual fields.

Example:

```
type FormValues = { todos: { label: string }[] };

const [form] = createForm<FormValues>({ initialValues: { todos: [] } );

// does not work
createEffect(on(
  // typescript also complains here about invalid paths
  () => getValue(form, "todos", { shouldActive: true }), 
  (next) => console.log(next)
));

// works
createEffect(on(
  () => getValue(form, "todos.0.label", { shouldActive: true }), 
  (next) => console.log(next)
));

```

Since typescript complains about the path "todos" being invalid, I guess that _I am doing it wrong_.
Is there a _right way_ to achieve what I am trying to achieve?

Stackblitz: https://stackblitz.com/edit/github-uzqzot-hc6xti?file=src%2FApp.tsx

**Comment by whytspace** [comment]
> true is the default value for shouldActive. Therefore, you do not need to specify it.

My bad, it's a remainder from when I tried if they make a difference in this case.

> I would add the initialValues option to createForm to display by default a field array item with fields that the user can type directly into.

@fabian-hiller you are right, I will add the new entry to initialValues. The way I did it (via `insert`) makes the form become dirty, which is not what I want.

But I would still like to automatically add a new entry as soon the previous one that gets dirty.


> getValues(form, "todos").length

I don't really want to react to the length changing. I need to react to the **content** changing. The length will stay the same, since the only way to add entries will be my automatic function that adds empty entries at the end.

---

But if that does not work, I will just add buttons to add a new line

**Comment by fabian-hiller** [comment]
Would the optimal development experience in your case be an `isDirty` method to react when a field or field array gets dirty? What action do you want to take when this case occurs?

**Comment by whytspace** [comment]
> Would the optimal development experience in your case be an isDirty method to react when a field or field array gets dirty

I think my desired behaviour is not very common, which is why I think a solution for it **belongs into userland** and does not need to ship with the plugin. However, it should be supported to implement this bahaviour.

My problem was not the functionality for checking if certain values are dirty (or empty, or whatever rule is needed); it was simply the fact that I **could not find a reactive preperty that I could listen to for running my custom function**.

**However, I just realized that I was using the wrong helper method all the time** 🤦. When I use `getValues` instead of `getValue`, I get exactly what I need: An effect that I can run whenever any value inside the `FieldArray` changes.
I thought that getValues was exclusively to get the whole form state…

```ts
// does not work. and shows a typescript error
createEffect(on( () => getValue(form, "todos"), (next) => console.log(next) ));

// works and shows no type error
createEffect(on( () => getValues(form, "todos"), (next) => console.log(next) ));
```

So consider this issue resolved.
