### ISSUE TITLE
FormError Class not in module

### ISSUE THREAD

**Issue by Excelsior2021** [fabian-hiller/modular-forms#94]
When I try to import the `FormError` class from `@modular-forms/solid` I get an error stating it does not exist in the module. I updated the module too. Please see the attached images.

<img width="883" alt="FormError SolidJS" src="https://github.com/fabian-hiller/modular-forms/assets/90631155/cd0648b3-6fd0-42d9-8c3c-a45aa552784c">
<img width="220" alt="Deps" src="https://github.com/fabian-hiller/modular-forms/assets/90631155/2854a4aa-f259-46cc-b44c-b1bb37509dbf">

**Comment by fabian-hiller** [comment]
Please update Modular Forms to the latest version and see the release notes or the changelog for more details.
