### ISSUE TITLE
Form component has `of` attribute with value of `[object Object]`

### ISSUE THREAD

**Issue by susickypavel** [fabian-hiller/modular-forms#98]
As mentioned in #92. It seems like the prop `of` is accidentally passed onto a form element and becomes an attribute, from what I can see, it is only used for the inner working of the library.

According to the example playground on stackblitz (with the latest versions of @modular-forms/x), it only affects SolidJS implementation.

I've looked into this a little bit, and it comes from https://github.com/fabian-hiller/modular-forms/blob/cb8f503c7571a6f6ac4656df2adeb048c21db32c/packages/solid/src/components/Form.tsx#L70

We should probably split the props one more time and spread only valid HTML attributes on the form. 

If you agree with the proposed solution or propose a better one, I can try to make PR to save you some time on more high-priority issues.

**Comment by fabian-hiller** [comment]
Fixed it. The change will go live with the next version.
